/**
 * Schema API handlers
 */

import { http, HttpResponse, delay } from 'msw'
import { getStore, getById, getSchemaBySourceId } from '../data/store'
import { createSchema, createId } from '../factories'

const API_BASE = '/api/v1'

export const schemasHandlers = [
  // Get schema for a source
  http.get(`${API_BASE}/sources/:sourceId/schema`, async ({ params }) => {
    await delay(150)

    const sourceId = params.sourceId as string
    const source = getById(getStore().sources, sourceId)

    if (!source) {
      return HttpResponse.json(
        { detail: 'Source not found' },
        { status: 404 }
      )
    }

    const schema = getSchemaBySourceId(sourceId)

    if (!schema) {
      return HttpResponse.json({
        success: true,
        data: null,
      })
    }

    return HttpResponse.json({
      success: true,
      data: schema,
    })
  }),

  // Learn schema for a source
  http.post(`${API_BASE}/sources/:sourceId/learn`, async ({ params }) => {
    await delay(1000) // Simulate learning time

    const sourceId = params.sourceId as string
    const source = getById(getStore().sources, sourceId)

    if (!source) {
      return HttpResponse.json(
        { detail: 'Source not found' },
        { status: 404 }
      )
    }

    // Create or update schema
    const schema = createSchema({
      id: createId(),
      sourceId,
    })

    getStore().schemas.set(sourceId, schema)

    // Update source's has_schema flag
    const sources = getStore().sources
    sources.set(sourceId, { ...source, has_schema: true })

    return HttpResponse.json({
      success: true,
      data: schema,
    })
  }),

  // Update schema
  http.put(`${API_BASE}/sources/:sourceId/schema`, async ({ params, request }) => {
    await delay(300)

    const sourceId = params.sourceId as string
    const source = getById(getStore().sources, sourceId)

    if (!source) {
      return HttpResponse.json(
        { detail: 'Source not found' },
        { status: 404 }
      )
    }

    let body: { schema_yaml: string }

    try {
      body = await request.json() as typeof body
    } catch {
      return HttpResponse.json(
        { detail: 'Invalid JSON in request body' },
        { status: 400 }
      )
    }

    // Validate schema_yaml is not empty
    if (!body.schema_yaml || body.schema_yaml.trim() === '') {
      return HttpResponse.json(
        { detail: 'schema_yaml cannot be empty' },
        { status: 400 }
      )
    }

    const existingSchema = getSchemaBySourceId(sourceId)

    // If no existing schema, create a new one with the provided YAML
    // The schema_json will be generated by createSchema and we update YAML
    const baseSchema = existingSchema ?? createSchema({ sourceId })

    const updatedSchema = {
      ...baseSchema,
      schema_yaml: body.schema_yaml,
      // Keep existing schema_json if available, as we can't easily parse YAML in browser
      // In real API, this would be parsed and synced
      updated_at: new Date().toISOString(),
    }

    getStore().schemas.set(sourceId, updatedSchema)

    // Update source's has_schema flag if it wasn't set
    const sources = getStore().sources
    const existingSource = sources.get(sourceId)
    if (existingSource && !existingSource.has_schema) {
      sources.set(sourceId, { ...existingSource, has_schema: true })
    }

    return HttpResponse.json({
      success: true,
      data: updatedSchema,
    })
  }),
]
