"""Distribution validators.

Validators for value ranges, statistical distributions, and outlier detection.
"""

from .base import (
    ParameterDefinition,
    ParameterType,
    ValidatorCategory,
    ValidatorDefinition,
)

DISTRIBUTION_VALIDATORS: list[ValidatorDefinition] = [
    ValidatorDefinition(
        name="Between",
        display_name="Value Between",
        category=ValidatorCategory.DISTRIBUTION,
        description="Validates that values fall within a specified range (inclusive).",
        parameters=[
            ParameterDefinition(
                name="column",
                label="Column",
                type=ParameterType.COLUMN,
                required=True,
            ),
            ParameterDefinition(
                name="min_value",
                label="Minimum Value",
                type=ParameterType.FLOAT,
                required=True,
            ),
            ParameterDefinition(
                name="max_value",
                label="Maximum Value",
                type=ParameterType.FLOAT,
                required=True,
            ),
            ParameterDefinition(
                name="mostly",
                label="Mostly (Threshold)",
                type=ParameterType.FLOAT,
                description="Acceptable pass ratio (0.0-1.0)",
                min_value=0,
                max_value=1,
            ),
        ],
        tags=["distribution", "range", "bounds"],
        severity_default="medium",
    ),
    ValidatorDefinition(
        name="Range",
        display_name="Range",
        category=ValidatorCategory.DISTRIBUTION,
        description="Validates value ranges with optional inclusivity control.",
        parameters=[
            ParameterDefinition(
                name="column",
                label="Column",
                type=ParameterType.COLUMN,
                required=True,
            ),
            ParameterDefinition(
                name="min_value",
                label="Minimum Value",
                type=ParameterType.FLOAT,
            ),
            ParameterDefinition(
                name="max_value",
                label="Maximum Value",
                type=ParameterType.FLOAT,
            ),
            ParameterDefinition(
                name="inclusive_min",
                label="Include Minimum",
                type=ParameterType.BOOLEAN,
                default=True,
            ),
            ParameterDefinition(
                name="inclusive_max",
                label="Include Maximum",
                type=ParameterType.BOOLEAN,
                default=True,
            ),
        ],
        tags=["distribution", "range", "bounds"],
        severity_default="medium",
    ),
    ValidatorDefinition(
        name="Positive",
        display_name="Positive Values",
        category=ValidatorCategory.DISTRIBUTION,
        description="Ensures all values are strictly positive (> 0).",
        parameters=[
            ParameterDefinition(
                name="column",
                label="Column",
                type=ParameterType.COLUMN,
                required=True,
            ),
        ],
        tags=["distribution", "positive", "numeric"],
        severity_default="high",
    ),
    ValidatorDefinition(
        name="NonNegative",
        display_name="Non-Negative Values",
        category=ValidatorCategory.DISTRIBUTION,
        description="Ensures all values are non-negative (>= 0).",
        parameters=[
            ParameterDefinition(
                name="column",
                label="Column",
                type=ParameterType.COLUMN,
                required=True,
            ),
        ],
        tags=["distribution", "non-negative", "numeric"],
        severity_default="high",
    ),
    ValidatorDefinition(
        name="InSet",
        display_name="In Set",
        category=ValidatorCategory.DISTRIBUTION,
        description="Validates that values belong to a predefined set.",
        parameters=[
            ParameterDefinition(
                name="column",
                label="Column",
                type=ParameterType.COLUMN,
                required=True,
            ),
            ParameterDefinition(
                name="value_set",
                label="Allowed Values",
                type=ParameterType.STRING_LIST,
                description="Set of allowed values",
                required=True,
            ),
            ParameterDefinition(
                name="mostly",
                label="Mostly (Threshold)",
                type=ParameterType.FLOAT,
                min_value=0,
                max_value=1,
            ),
        ],
        tags=["distribution", "set", "enum"],
        severity_default="medium",
    ),
    ValidatorDefinition(
        name="NotInSet",
        display_name="Not In Set",
        category=ValidatorCategory.DISTRIBUTION,
        description="Ensures values do not belong to a forbidden set.",
        parameters=[
            ParameterDefinition(
                name="column",
                label="Column",
                type=ParameterType.COLUMN,
                required=True,
            ),
            ParameterDefinition(
                name="forbidden_set",
                label="Forbidden Values",
                type=ParameterType.STRING_LIST,
                description="Set of forbidden values",
                required=True,
            ),
        ],
        tags=["distribution", "set", "forbidden"],
        severity_default="high",
    ),
    ValidatorDefinition(
        name="Increasing",
        display_name="Increasing",
        category=ValidatorCategory.DISTRIBUTION,
        description="Validates that values are monotonically increasing.",
        parameters=[
            ParameterDefinition(
                name="column",
                label="Column",
                type=ParameterType.COLUMN,
                required=True,
            ),
            ParameterDefinition(
                name="strict",
                label="Strictly Increasing",
                type=ParameterType.BOOLEAN,
                description="If true, values must be strictly increasing (no equal values)",
                default=False,
            ),
        ],
        tags=["distribution", "monotonic", "increasing"],
        severity_default="medium",
    ),
    ValidatorDefinition(
        name="Decreasing",
        display_name="Decreasing",
        category=ValidatorCategory.DISTRIBUTION,
        description="Validates that values are monotonically decreasing.",
        parameters=[
            ParameterDefinition(
                name="column",
                label="Column",
                type=ParameterType.COLUMN,
                required=True,
            ),
            ParameterDefinition(
                name="strict",
                label="Strictly Decreasing",
                type=ParameterType.BOOLEAN,
                default=False,
            ),
        ],
        tags=["distribution", "monotonic", "decreasing"],
        severity_default="medium",
    ),
    ValidatorDefinition(
        name="Outlier",
        display_name="Outlier (IQR)",
        category=ValidatorCategory.DISTRIBUTION,
        description="Detects statistical outliers using the IQR method.",
        parameters=[
            ParameterDefinition(
                name="column",
                label="Column",
                type=ParameterType.COLUMN,
                required=True,
            ),
            ParameterDefinition(
                name="iqr_multiplier",
                label="IQR Multiplier",
                type=ParameterType.FLOAT,
                description="Multiplier for IQR (1.5 = standard, 3.0 = extreme)",
                default=1.5,
                min_value=0,
            ),
        ],
        tags=["distribution", "outlier", "iqr", "anomaly"],
        severity_default="medium",
    ),
    ValidatorDefinition(
        name="ZScoreOutlier",
        display_name="Outlier (Z-Score)",
        category=ValidatorCategory.DISTRIBUTION,
        description="Detects outliers using Z-score methodology.",
        parameters=[
            ParameterDefinition(
                name="column",
                label="Column",
                type=ParameterType.COLUMN,
                required=True,
            ),
            ParameterDefinition(
                name="threshold",
                label="Z-Score Threshold",
                type=ParameterType.FLOAT,
                description="Z-score threshold (default: 3.0)",
                default=3.0,
                min_value=0,
            ),
        ],
        tags=["distribution", "outlier", "zscore", "anomaly"],
        severity_default="medium",
    ),
    ValidatorDefinition(
        name="Quantile",
        display_name="Quantile",
        category=ValidatorCategory.DISTRIBUTION,
        description="Validates that values fall within specified quantile bounds.",
        parameters=[
            ParameterDefinition(
                name="column",
                label="Column",
                type=ParameterType.COLUMN,
                required=True,
            ),
            ParameterDefinition(
                name="quantile",
                label="Quantile",
                type=ParameterType.FLOAT,
                description="Quantile value (0.0-1.0, e.g., 0.95 for 95th percentile)",
                required=True,
                min_value=0,
                max_value=1,
            ),
            ParameterDefinition(
                name="max_value",
                label="Maximum Value at Quantile",
                type=ParameterType.FLOAT,
                description="Maximum allowed value at the specified quantile",
                required=True,
            ),
        ],
        tags=["distribution", "quantile", "percentile"],
        severity_default="medium",
    ),
    ValidatorDefinition(
        name="Distribution",
        display_name="Distribution",
        category=ValidatorCategory.DISTRIBUTION,
        description="Validates that data follows an expected distribution pattern.",
        parameters=[
            ParameterDefinition(
                name="column",
                label="Column",
                type=ParameterType.COLUMN,
                required=True,
            ),
            ParameterDefinition(
                name="distribution",
                label="Expected Distribution",
                type=ParameterType.SELECT,
                description="Expected distribution type",
                required=True,
                options=[
                    {"value": "normal", "label": "Normal (Gaussian)"},
                    {"value": "uniform", "label": "Uniform"},
                    {"value": "exponential", "label": "Exponential"},
                    {"value": "poisson", "label": "Poisson"},
                    {"value": "binomial", "label": "Binomial"},
                ],
            ),
        ],
        tags=["distribution", "statistical", "pattern"],
        severity_default="low",
    ),
    ValidatorDefinition(
        name="KLDivergence",
        display_name="KL Divergence",
        category=ValidatorCategory.DISTRIBUTION,
        description="Validates distribution similarity using Kullback-Leibler divergence.",
        parameters=[
            ParameterDefinition(
                name="column",
                label="Column",
                type=ParameterType.COLUMN,
                required=True,
            ),
            ParameterDefinition(
                name="reference_distribution",
                label="Reference Distribution",
                type=ParameterType.SCHEMA,
                description="Reference probability distribution as JSON",
                required=True,
                placeholder='{"A": 0.5, "B": 0.3, "C": 0.2}',
            ),
            ParameterDefinition(
                name="threshold",
                label="Threshold",
                type=ParameterType.FLOAT,
                description="Maximum allowed KL divergence",
                required=True,
                default=0.1,
                min_value=0,
            ),
        ],
        tags=["distribution", "kl", "divergence", "statistical"],
        severity_default="medium",
    ),
    ValidatorDefinition(
        name="ChiSquare",
        display_name="Chi-Square Test",
        category=ValidatorCategory.DISTRIBUTION,
        description="Performs chi-square goodness-of-fit testing.",
        parameters=[
            ParameterDefinition(
                name="column",
                label="Column",
                type=ParameterType.COLUMN,
                required=True,
            ),
            ParameterDefinition(
                name="expected_frequencies",
                label="Expected Frequencies",
                type=ParameterType.SCHEMA,
                description="Expected frequency distribution as JSON",
                required=True,
            ),
            ParameterDefinition(
                name="alpha",
                label="Significance Level",
                type=ParameterType.FLOAT,
                description="Significance level (default: 0.05)",
                default=0.05,
                min_value=0,
                max_value=1,
            ),
        ],
        tags=["distribution", "chi-square", "statistical", "test"],
        severity_default="medium",
    ),
    ValidatorDefinition(
        name="MostCommonValue",
        display_name="Most Common Value",
        category=ValidatorCategory.DISTRIBUTION,
        description="Validates the most common value and its frequency.",
        parameters=[
            ParameterDefinition(
                name="column",
                label="Column",
                type=ParameterType.COLUMN,
                required=True,
            ),
            ParameterDefinition(
                name="expected_value",
                label="Expected Most Common Value",
                type=ParameterType.STRING,
            ),
            ParameterDefinition(
                name="min_frequency",
                label="Minimum Frequency",
                type=ParameterType.FLOAT,
                description="Minimum frequency ratio (0.0-1.0)",
                min_value=0,
                max_value=1,
            ),
        ],
        tags=["distribution", "frequency", "mode"],
        severity_default="low",
    ),
]
