"""Geospatial validators.

Validators for geographic coordinate and spatial data validation.
"""

from .base import (
    ParameterDefinition,
    ParameterType,
    ValidatorCategory,
    ValidatorDefinition,
)

GEOSPATIAL_VALIDATORS: list[ValidatorDefinition] = [
    ValidatorDefinition(
        name="Latitude",
        display_name="Latitude Bounds",
        category=ValidatorCategory.GEOSPATIAL,
        description="Validates latitude values are within valid bounds (-90 to 90).",
        parameters=[
            ParameterDefinition(
                name="column",
                label="Latitude Column",
                type=ParameterType.COLUMN,
                required=True,
            ),
            ParameterDefinition(
                name="min_lat",
                label="Minimum Latitude",
                type=ParameterType.FLOAT,
                default=-90.0,
                min_value=-90,
                max_value=90,
            ),
            ParameterDefinition(
                name="max_lat",
                label="Maximum Latitude",
                type=ParameterType.FLOAT,
                default=90.0,
                min_value=-90,
                max_value=90,
            ),
        ],
        tags=["geospatial", "latitude", "coordinate"],
        severity_default="medium",
    ),
    ValidatorDefinition(
        name="Longitude",
        display_name="Longitude Bounds",
        category=ValidatorCategory.GEOSPATIAL,
        description="Validates longitude values are within valid bounds (-180 to 180).",
        parameters=[
            ParameterDefinition(
                name="column",
                label="Longitude Column",
                type=ParameterType.COLUMN,
                required=True,
            ),
            ParameterDefinition(
                name="min_lon",
                label="Minimum Longitude",
                type=ParameterType.FLOAT,
                default=-180.0,
                min_value=-180,
                max_value=180,
            ),
            ParameterDefinition(
                name="max_lon",
                label="Maximum Longitude",
                type=ParameterType.FLOAT,
                default=180.0,
                min_value=-180,
                max_value=180,
            ),
        ],
        tags=["geospatial", "longitude", "coordinate"],
        severity_default="medium",
    ),
    ValidatorDefinition(
        name="Coordinate",
        display_name="Coordinate Pair",
        category=ValidatorCategory.GEOSPATIAL,
        description="Validates latitude/longitude coordinate pairs.",
        parameters=[
            ParameterDefinition(
                name="lat_column",
                label="Latitude Column",
                type=ParameterType.COLUMN,
                required=True,
            ),
            ParameterDefinition(
                name="lon_column",
                label="Longitude Column",
                type=ParameterType.COLUMN,
                required=True,
            ),
        ],
        tags=["geospatial", "coordinate", "pair"],
        severity_default="medium",
    ),
    ValidatorDefinition(
        name="CoordinateNotNullIsland",
        display_name="Not Null Island",
        category=ValidatorCategory.GEOSPATIAL,
        description="Detects coordinates at (0, 0) - common placeholder or error.",
        parameters=[
            ParameterDefinition(
                name="lat_column",
                label="Latitude Column",
                type=ParameterType.COLUMN,
                required=True,
            ),
            ParameterDefinition(
                name="lon_column",
                label="Longitude Column",
                type=ParameterType.COLUMN,
                required=True,
            ),
            ParameterDefinition(
                name="tolerance",
                label="Tolerance (degrees)",
                type=ParameterType.FLOAT,
                description="Tolerance around (0,0) to flag",
                default=0.001,
                min_value=0,
            ),
        ],
        tags=["geospatial", "null_island", "quality"],
        severity_default="medium",
    ),
    ValidatorDefinition(
        name="GeoDistance",
        display_name="Distance Between Points",
        category=ValidatorCategory.GEOSPATIAL,
        description="Validates distance between two coordinate pairs.",
        parameters=[
            ParameterDefinition(
                name="lat_column_a",
                label="Latitude A",
                type=ParameterType.COLUMN,
                required=True,
            ),
            ParameterDefinition(
                name="lon_column_a",
                label="Longitude A",
                type=ParameterType.COLUMN,
                required=True,
            ),
            ParameterDefinition(
                name="lat_column_b",
                label="Latitude B",
                type=ParameterType.COLUMN,
                required=True,
            ),
            ParameterDefinition(
                name="lon_column_b",
                label="Longitude B",
                type=ParameterType.COLUMN,
                required=True,
            ),
            ParameterDefinition(
                name="max_distance_km",
                label="Max Distance (km)",
                type=ParameterType.FLOAT,
                description="Maximum allowed distance in kilometers",
                required=True,
                min_value=0,
            ),
        ],
        tags=["geospatial", "distance", "haversine"],
        severity_default="medium",
    ),
    ValidatorDefinition(
        name="GeoDistanceFromPoint",
        display_name="Distance From Reference Point",
        category=ValidatorCategory.GEOSPATIAL,
        description="Validates distance from a fixed reference point.",
        parameters=[
            ParameterDefinition(
                name="lat_column",
                label="Latitude Column",
                type=ParameterType.COLUMN,
                required=True,
            ),
            ParameterDefinition(
                name="lon_column",
                label="Longitude Column",
                type=ParameterType.COLUMN,
                required=True,
            ),
            ParameterDefinition(
                name="reference_lat",
                label="Reference Latitude",
                type=ParameterType.FLOAT,
                required=True,
                min_value=-90,
                max_value=90,
            ),
            ParameterDefinition(
                name="reference_lon",
                label="Reference Longitude",
                type=ParameterType.FLOAT,
                required=True,
                min_value=-180,
                max_value=180,
            ),
            ParameterDefinition(
                name="max_distance_km",
                label="Max Distance (km)",
                type=ParameterType.FLOAT,
                required=True,
                min_value=0,
            ),
        ],
        tags=["geospatial", "distance", "reference"],
        severity_default="medium",
    ),
    ValidatorDefinition(
        name="GeoBoundingBox",
        display_name="Bounding Box",
        category=ValidatorCategory.GEOSPATIAL,
        description="Validates coordinates fall within a bounding box.",
        parameters=[
            ParameterDefinition(
                name="lat_column",
                label="Latitude Column",
                type=ParameterType.COLUMN,
                required=True,
            ),
            ParameterDefinition(
                name="lon_column",
                label="Longitude Column",
                type=ParameterType.COLUMN,
                required=True,
            ),
            ParameterDefinition(
                name="min_lat",
                label="Min Latitude (South)",
                type=ParameterType.FLOAT,
                required=True,
                min_value=-90,
                max_value=90,
            ),
            ParameterDefinition(
                name="max_lat",
                label="Max Latitude (North)",
                type=ParameterType.FLOAT,
                required=True,
                min_value=-90,
                max_value=90,
            ),
            ParameterDefinition(
                name="min_lon",
                label="Min Longitude (West)",
                type=ParameterType.FLOAT,
                required=True,
                min_value=-180,
                max_value=180,
            ),
            ParameterDefinition(
                name="max_lon",
                label="Max Longitude (East)",
                type=ParameterType.FLOAT,
                required=True,
                min_value=-180,
                max_value=180,
            ),
        ],
        tags=["geospatial", "bounding_box", "region"],
        severity_default="medium",
    ),
    ValidatorDefinition(
        name="GeoCountry",
        display_name="Country Bounds",
        category=ValidatorCategory.GEOSPATIAL,
        description="Validates coordinates fall within a country's boundaries.",
        parameters=[
            ParameterDefinition(
                name="lat_column",
                label="Latitude Column",
                type=ParameterType.COLUMN,
                required=True,
            ),
            ParameterDefinition(
                name="lon_column",
                label="Longitude Column",
                type=ParameterType.COLUMN,
                required=True,
            ),
            ParameterDefinition(
                name="country_code",
                label="Country Code",
                type=ParameterType.SELECT,
                description="ISO 3166-1 alpha-2 country code",
                required=True,
                options=[
                    {"value": "US", "label": "United States"},
                    {"value": "KR", "label": "South Korea"},
                    {"value": "JP", "label": "Japan"},
                    {"value": "CN", "label": "China"},
                    {"value": "DE", "label": "Germany"},
                    {"value": "FR", "label": "France"},
                    {"value": "GB", "label": "United Kingdom"},
                    {"value": "CA", "label": "Canada"},
                    {"value": "AU", "label": "Australia"},
                    {"value": "BR", "label": "Brazil"},
                    {"value": "IN", "label": "India"},
                ],
            ),
            ParameterDefinition(
                name="use_approximate",
                label="Use Approximate Bounds",
                type=ParameterType.BOOLEAN,
                description="Use bounding box instead of precise borders",
                default=True,
            ),
        ],
        tags=["geospatial", "country", "bounds"],
        severity_default="medium",
    ),
    ValidatorDefinition(
        name="GeoPolygon",
        display_name="Within Polygon",
        category=ValidatorCategory.GEOSPATIAL,
        description="Validates coordinates fall within a custom polygon.",
        parameters=[
            ParameterDefinition(
                name="lat_column",
                label="Latitude Column",
                type=ParameterType.COLUMN,
                required=True,
            ),
            ParameterDefinition(
                name="lon_column",
                label="Longitude Column",
                type=ParameterType.COLUMN,
                required=True,
            ),
            ParameterDefinition(
                name="polygon",
                label="Polygon Coordinates",
                type=ParameterType.SCHEMA,
                description="GeoJSON polygon coordinates",
                required=True,
                placeholder='[[[-122.4, 37.8], [-122.4, 37.7], [-122.3, 37.7], [-122.3, 37.8]]]',
            ),
        ],
        tags=["geospatial", "polygon", "custom"],
        severity_default="medium",
    ),
    ValidatorDefinition(
        name="GeoCluster",
        display_name="Geographic Clustering",
        category=ValidatorCategory.GEOSPATIAL,
        description="Validates geographic clustering properties.",
        parameters=[
            ParameterDefinition(
                name="lat_column",
                label="Latitude Column",
                type=ParameterType.COLUMN,
                required=True,
            ),
            ParameterDefinition(
                name="lon_column",
                label="Longitude Column",
                type=ParameterType.COLUMN,
                required=True,
            ),
            ParameterDefinition(
                name="max_cluster_radius_km",
                label="Max Cluster Radius (km)",
                type=ParameterType.FLOAT,
                description="Maximum expected radius of data clusters",
                min_value=0,
            ),
            ParameterDefinition(
                name="min_points_per_cluster",
                label="Min Points Per Cluster",
                type=ParameterType.INTEGER,
                default=1,
                min_value=1,
            ),
        ],
        tags=["geospatial", "clustering", "density"],
        severity_default="low",
    ),
    ValidatorDefinition(
        name="GeoSpeed",
        display_name="Geographic Speed",
        category=ValidatorCategory.GEOSPATIAL,
        description="Validates travel speed between sequential coordinates.",
        parameters=[
            ParameterDefinition(
                name="lat_column",
                label="Latitude Column",
                type=ParameterType.COLUMN,
                required=True,
            ),
            ParameterDefinition(
                name="lon_column",
                label="Longitude Column",
                type=ParameterType.COLUMN,
                required=True,
            ),
            ParameterDefinition(
                name="timestamp_column",
                label="Timestamp Column",
                type=ParameterType.COLUMN,
                required=True,
            ),
            ParameterDefinition(
                name="max_speed_kmh",
                label="Max Speed (km/h)",
                type=ParameterType.FLOAT,
                description="Maximum realistic travel speed",
                default=200,
                min_value=0,
            ),
            ParameterDefinition(
                name="entity_column",
                label="Entity Column",
                type=ParameterType.COLUMN,
                description="Column to group by (e.g., vehicle_id)",
            ),
        ],
        tags=["geospatial", "speed", "trajectory"],
        severity_default="medium",
    ),
    ValidatorDefinition(
        name="GeoAltitude",
        display_name="Altitude Bounds",
        category=ValidatorCategory.GEOSPATIAL,
        description="Validates altitude/elevation values.",
        parameters=[
            ParameterDefinition(
                name="column",
                label="Altitude Column",
                type=ParameterType.COLUMN,
                required=True,
            ),
            ParameterDefinition(
                name="min_altitude",
                label="Minimum Altitude (m)",
                type=ParameterType.FLOAT,
                description="Minimum altitude in meters",
                default=-500,
            ),
            ParameterDefinition(
                name="max_altitude",
                label="Maximum Altitude (m)",
                type=ParameterType.FLOAT,
                description="Maximum altitude in meters",
                default=10000,
            ),
        ],
        tags=["geospatial", "altitude", "elevation"],
        severity_default="low",
    ),
    ValidatorDefinition(
        name="GeoTimezone",
        display_name="Timezone Consistency",
        category=ValidatorCategory.GEOSPATIAL,
        description="Validates timezone consistency with geographic location.",
        parameters=[
            ParameterDefinition(
                name="lat_column",
                label="Latitude Column",
                type=ParameterType.COLUMN,
                required=True,
            ),
            ParameterDefinition(
                name="lon_column",
                label="Longitude Column",
                type=ParameterType.COLUMN,
                required=True,
            ),
            ParameterDefinition(
                name="timezone_column",
                label="Timezone Column",
                type=ParameterType.COLUMN,
                required=True,
            ),
        ],
        tags=["geospatial", "timezone", "consistency"],
        severity_default="low",
    ),
]
