"""ML Feature validators.

Validators for machine learning feature quality including null impact,
scale validation, correlation analysis, and target leakage detection.

Import path in truthound: `from truthound.validators.ml_feature import *`
"""

from .base import (
    ParameterDefinition,
    ParameterType,
    ValidatorCategory,
    ValidatorDefinition,
)

ML_FEATURE_VALIDATORS: list[ValidatorDefinition] = [
    ValidatorDefinition(
        name="FeatureNullImpact",
        display_name="Feature Null Impact Analysis",
        category=ValidatorCategory.ML_FEATURE,
        description="Analyzes and validates the impact of null values on ML features.",
        parameters=[
            ParameterDefinition(
                name="column",
                label="Feature Column",
                type=ParameterType.COLUMN,
                required=True,
                description="Feature column to analyze",
            ),
            ParameterDefinition(
                name="target_column",
                label="Target Column",
                type=ParameterType.COLUMN,
                description="Target column for impact analysis",
            ),
            ParameterDefinition(
                name="max_null_ratio",
                label="Maximum Null Ratio",
                type=ParameterType.FLOAT,
                default=0.1,
                min_value=0,
                max_value=1,
                description="Maximum acceptable ratio of null values",
            ),
            ParameterDefinition(
                name="max_impact_score",
                label="Maximum Impact Score",
                type=ParameterType.FLOAT,
                min_value=0,
                max_value=1,
                description="Maximum acceptable impact score on target",
            ),
        ],
        tags=["ml_feature", "null", "impact", "missing"],
        severity_default="medium",
    ),
    ValidatorDefinition(
        name="FeatureScale",
        display_name="Feature Scale Validation",
        category=ValidatorCategory.ML_FEATURE,
        description="Validates that features are properly scaled for ML algorithms.",
        parameters=[
            ParameterDefinition(
                name="column",
                label="Feature Column",
                type=ParameterType.COLUMN,
                required=True,
                description="Feature column to validate",
            ),
            ParameterDefinition(
                name="expected_scale",
                label="Expected Scale Type",
                type=ParameterType.SELECT,
                options=[
                    {"value": "standard", "label": "Standard (mean=0, std=1)"},
                    {"value": "minmax", "label": "Min-Max (0 to 1)"},
                    {"value": "robust", "label": "Robust (median-centered)"},
                    {"value": "unit_norm", "label": "Unit Norm (L2=1)"},
                ],
                required=True,
                description="Expected feature scale type",
            ),
            ParameterDefinition(
                name="tolerance",
                label="Tolerance",
                type=ParameterType.FLOAT,
                default=0.1,
                min_value=0,
                max_value=1,
                description="Acceptable deviation from expected scale",
            ),
        ],
        tags=["ml_feature", "scale", "normalization", "preprocessing"],
        severity_default="medium",
    ),
    ValidatorDefinition(
        name="FeatureCorrelationMatrix",
        display_name="Feature Correlation Matrix",
        category=ValidatorCategory.ML_FEATURE,
        description="Validates correlation between features for multicollinearity detection.",
        parameters=[
            ParameterDefinition(
                name="columns",
                label="Feature Columns",
                type=ParameterType.COLUMN_LIST,
                required=True,
                description="Feature columns to analyze correlation",
            ),
            ParameterDefinition(
                name="max_correlation",
                label="Maximum Correlation",
                type=ParameterType.FLOAT,
                default=0.9,
                min_value=0,
                max_value=1,
                description="Maximum acceptable absolute correlation between features",
            ),
            ParameterDefinition(
                name="method",
                label="Correlation Method",
                type=ParameterType.SELECT,
                options=[
                    {"value": "pearson", "label": "Pearson"},
                    {"value": "spearman", "label": "Spearman"},
                    {"value": "kendall", "label": "Kendall"},
                ],
                default="pearson",
                description="Correlation calculation method",
            ),
        ],
        tags=["ml_feature", "correlation", "multicollinearity", "redundancy"],
        severity_default="medium",
    ),
    ValidatorDefinition(
        name="TargetLeakage",
        display_name="Target Leakage Detection",
        category=ValidatorCategory.ML_FEATURE,
        description="Detects potential target leakage in features.",
        parameters=[
            ParameterDefinition(
                name="feature_columns",
                label="Feature Columns",
                type=ParameterType.COLUMN_LIST,
                required=True,
                description="Feature columns to check for leakage",
            ),
            ParameterDefinition(
                name="target_column",
                label="Target Column",
                type=ParameterType.COLUMN,
                required=True,
                description="Target column",
            ),
            ParameterDefinition(
                name="leakage_threshold",
                label="Leakage Threshold",
                type=ParameterType.FLOAT,
                default=0.95,
                min_value=0.5,
                max_value=1,
                description="Correlation threshold indicating potential leakage",
            ),
        ],
        tags=["ml_feature", "leakage", "target", "data_leakage"],
        severity_default="critical",
    ),
    ValidatorDefinition(
        name="FeatureImportance",
        display_name="Feature Importance Threshold",
        category=ValidatorCategory.ML_FEATURE,
        description="Validates minimum feature importance for ML model utility.",
        parameters=[
            ParameterDefinition(
                name="column",
                label="Feature Column",
                type=ParameterType.COLUMN,
                required=True,
                description="Feature column to validate",
            ),
            ParameterDefinition(
                name="target_column",
                label="Target Column",
                type=ParameterType.COLUMN,
                required=True,
                description="Target column for importance calculation",
            ),
            ParameterDefinition(
                name="min_importance",
                label="Minimum Importance",
                type=ParameterType.FLOAT,
                default=0.01,
                min_value=0,
                max_value=1,
                description="Minimum required feature importance score",
            ),
            ParameterDefinition(
                name="method",
                label="Importance Method",
                type=ParameterType.SELECT,
                options=[
                    {"value": "mutual_info", "label": "Mutual Information"},
                    {"value": "correlation", "label": "Correlation"},
                    {"value": "f_score", "label": "F-Score (ANOVA)"},
                ],
                default="mutual_info",
                description="Method for calculating feature importance",
            ),
        ],
        tags=["ml_feature", "importance", "relevance", "selection"],
        severity_default="low",
    ),
    ValidatorDefinition(
        name="FeatureVariance",
        display_name="Feature Variance Threshold",
        category=ValidatorCategory.ML_FEATURE,
        description="Validates minimum feature variance (removes near-constant features).",
        parameters=[
            ParameterDefinition(
                name="column",
                label="Feature Column",
                type=ParameterType.COLUMN,
                required=True,
                description="Feature column to validate",
            ),
            ParameterDefinition(
                name="min_variance",
                label="Minimum Variance",
                type=ParameterType.FLOAT,
                default=0.01,
                min_value=0,
                description="Minimum required variance",
            ),
        ],
        tags=["ml_feature", "variance", "constant", "low_variance"],
        severity_default="medium",
    ),
    ValidatorDefinition(
        name="FeatureOutlierRatio",
        display_name="Feature Outlier Ratio",
        category=ValidatorCategory.ML_FEATURE,
        description="Validates that outlier ratio in features is within acceptable bounds.",
        parameters=[
            ParameterDefinition(
                name="column",
                label="Feature Column",
                type=ParameterType.COLUMN,
                required=True,
                description="Feature column to check",
            ),
            ParameterDefinition(
                name="max_outlier_ratio",
                label="Maximum Outlier Ratio",
                type=ParameterType.FLOAT,
                default=0.05,
                min_value=0,
                max_value=1,
                description="Maximum acceptable ratio of outliers",
            ),
            ParameterDefinition(
                name="method",
                label="Outlier Detection Method",
                type=ParameterType.SELECT,
                options=[
                    {"value": "iqr", "label": "IQR (1.5x)"},
                    {"value": "zscore", "label": "Z-Score (3 sigma)"},
                    {"value": "mad", "label": "MAD"},
                ],
                default="iqr",
                description="Method for outlier detection",
            ),
        ],
        tags=["ml_feature", "outlier", "anomaly", "preprocessing"],
        severity_default="medium",
    ),
    ValidatorDefinition(
        name="ClassImbalance",
        display_name="Class Imbalance Check",
        category=ValidatorCategory.ML_FEATURE,
        description="Validates class distribution for classification targets.",
        parameters=[
            ParameterDefinition(
                name="column",
                label="Target Column",
                type=ParameterType.COLUMN,
                required=True,
                description="Classification target column",
            ),
            ParameterDefinition(
                name="max_imbalance_ratio",
                label="Maximum Imbalance Ratio",
                type=ParameterType.FLOAT,
                default=10,
                min_value=1,
                description="Maximum ratio of majority to minority class",
            ),
            ParameterDefinition(
                name="min_samples_per_class",
                label="Minimum Samples per Class",
                type=ParameterType.INTEGER,
                default=10,
                min_value=1,
                description="Minimum required samples for each class",
            ),
        ],
        tags=["ml_feature", "class_imbalance", "target", "classification"],
        severity_default="high",
    ),
]
