"""Profiling validators.

Validators for data profiling metrics including cardinality, entropy,
and value frequency distributions.

Import path in truthound: `from truthound.validators.profiling import *`
"""

from .base import (
    ParameterDefinition,
    ParameterType,
    ValidatorCategory,
    ValidatorDefinition,
)

PROFILING_VALIDATORS: list[ValidatorDefinition] = [
    ValidatorDefinition(
        name="Cardinality",
        display_name="Cardinality Validation",
        category=ValidatorCategory.PROFILING,
        description="Validates that column cardinality (distinct count) falls within expected bounds.",
        parameters=[
            ParameterDefinition(
                name="column",
                label="Column",
                type=ParameterType.COLUMN,
                required=True,
                description="Column to check cardinality",
            ),
            ParameterDefinition(
                name="min_cardinality",
                label="Minimum Cardinality",
                type=ParameterType.INTEGER,
                min_value=0,
                description="Minimum expected distinct values",
            ),
            ParameterDefinition(
                name="max_cardinality",
                label="Maximum Cardinality",
                type=ParameterType.INTEGER,
                min_value=0,
                description="Maximum expected distinct values",
            ),
        ],
        tags=["profiling", "cardinality", "distinct", "count"],
        severity_default="medium",
    ),
    ValidatorDefinition(
        name="UniquenessRatio",
        display_name="Uniqueness Ratio",
        category=ValidatorCategory.PROFILING,
        description="Validates that the ratio of unique values to total values meets expectations.",
        parameters=[
            ParameterDefinition(
                name="column",
                label="Column",
                type=ParameterType.COLUMN,
                required=True,
                description="Column to analyze",
            ),
            ParameterDefinition(
                name="min_ratio",
                label="Minimum Ratio",
                type=ParameterType.FLOAT,
                min_value=0,
                max_value=1,
                description="Minimum uniqueness ratio (0-1)",
            ),
            ParameterDefinition(
                name="max_ratio",
                label="Maximum Ratio",
                type=ParameterType.FLOAT,
                min_value=0,
                max_value=1,
                description="Maximum uniqueness ratio (0-1)",
            ),
        ],
        tags=["profiling", "uniqueness", "ratio", "distinct"],
        severity_default="medium",
    ),
    ValidatorDefinition(
        name="Entropy",
        display_name="Shannon Entropy",
        category=ValidatorCategory.PROFILING,
        description="Validates that column Shannon entropy falls within expected bounds.",
        parameters=[
            ParameterDefinition(
                name="column",
                label="Column",
                type=ParameterType.COLUMN,
                required=True,
                description="Column to calculate entropy",
            ),
            ParameterDefinition(
                name="min_entropy",
                label="Minimum Entropy",
                type=ParameterType.FLOAT,
                min_value=0,
                description="Minimum expected entropy (bits)",
            ),
            ParameterDefinition(
                name="max_entropy",
                label="Maximum Entropy",
                type=ParameterType.FLOAT,
                min_value=0,
                description="Maximum expected entropy (bits)",
            ),
        ],
        tags=["profiling", "entropy", "information", "randomness"],
        severity_default="medium",
    ),
    ValidatorDefinition(
        name="InformationGain",
        display_name="Information Gain",
        category=ValidatorCategory.PROFILING,
        description="Validates information gain between two columns (for feature selection).",
        parameters=[
            ParameterDefinition(
                name="feature_column",
                label="Feature Column",
                type=ParameterType.COLUMN,
                required=True,
                description="Feature column",
            ),
            ParameterDefinition(
                name="target_column",
                label="Target Column",
                type=ParameterType.COLUMN,
                required=True,
                description="Target column",
            ),
            ParameterDefinition(
                name="min_gain",
                label="Minimum Gain",
                type=ParameterType.FLOAT,
                min_value=0,
                description="Minimum required information gain",
            ),
        ],
        tags=["profiling", "information_gain", "feature", "ml"],
        severity_default="low",
    ),
    ValidatorDefinition(
        name="ValueFrequency",
        display_name="Value Frequency Distribution",
        category=ValidatorCategory.PROFILING,
        description="Validates that value frequency distribution meets expectations.",
        parameters=[
            ParameterDefinition(
                name="column",
                label="Column",
                type=ParameterType.COLUMN,
                required=True,
                description="Column to analyze",
            ),
            ParameterDefinition(
                name="expected_distribution",
                label="Expected Distribution",
                type=ParameterType.SELECT,
                options=[
                    {"value": "uniform", "label": "Uniform"},
                    {"value": "normal", "label": "Normal (Gaussian)"},
                    {"value": "exponential", "label": "Exponential"},
                    {"value": "power_law", "label": "Power Law (Zipf)"},
                ],
                default="uniform",
                description="Expected frequency distribution type",
            ),
            ParameterDefinition(
                name="tolerance",
                label="Tolerance",
                type=ParameterType.FLOAT,
                default=0.1,
                min_value=0,
                max_value=1,
                description="Acceptable deviation from expected distribution",
            ),
        ],
        tags=["profiling", "frequency", "distribution", "histogram"],
        severity_default="low",
    ),
    ValidatorDefinition(
        name="DistributionShape",
        display_name="Distribution Shape",
        category=ValidatorCategory.PROFILING,
        description="Validates the shape of value distribution (skewness, kurtosis).",
        parameters=[
            ParameterDefinition(
                name="column",
                label="Column",
                type=ParameterType.COLUMN,
                required=True,
                description="Column to analyze",
            ),
            ParameterDefinition(
                name="max_skewness",
                label="Maximum Skewness",
                type=ParameterType.FLOAT,
                description="Maximum acceptable skewness (absolute value)",
            ),
            ParameterDefinition(
                name="max_kurtosis",
                label="Maximum Kurtosis",
                type=ParameterType.FLOAT,
                description="Maximum acceptable excess kurtosis",
            ),
        ],
        tags=["profiling", "distribution", "skewness", "kurtosis"],
        severity_default="low",
    ),
    ValidatorDefinition(
        name="MostCommonValue",
        display_name="Most Common Value Check",
        category=ValidatorCategory.PROFILING,
        description="Validates the most common value and its frequency.",
        parameters=[
            ParameterDefinition(
                name="column",
                label="Column",
                type=ParameterType.COLUMN,
                required=True,
                description="Column to analyze",
            ),
            ParameterDefinition(
                name="expected_value",
                label="Expected Most Common Value",
                type=ParameterType.STRING,
                description="Expected most common value (optional)",
            ),
            ParameterDefinition(
                name="max_frequency_ratio",
                label="Maximum Frequency Ratio",
                type=ParameterType.FLOAT,
                min_value=0,
                max_value=1,
                description="Maximum ratio of most common value (detect imbalance)",
            ),
        ],
        tags=["profiling", "mode", "common", "frequency"],
        severity_default="low",
    ),
    ValidatorDefinition(
        name="DataTypeConsistency",
        display_name="Data Type Consistency",
        category=ValidatorCategory.PROFILING,
        description="Validates that inferred data types are consistent with expected types.",
        parameters=[
            ParameterDefinition(
                name="column",
                label="Column",
                type=ParameterType.COLUMN,
                required=True,
                description="Column to validate",
            ),
            ParameterDefinition(
                name="expected_type",
                label="Expected Data Type",
                type=ParameterType.SELECT,
                options=[
                    {"value": "integer", "label": "Integer"},
                    {"value": "float", "label": "Float"},
                    {"value": "string", "label": "String"},
                    {"value": "boolean", "label": "Boolean"},
                    {"value": "date", "label": "Date"},
                    {"value": "datetime", "label": "DateTime"},
                    {"value": "categorical", "label": "Categorical"},
                ],
                required=True,
                description="Expected inferred data type",
            ),
        ],
        tags=["profiling", "type", "consistency", "inference"],
        severity_default="medium",
    ),
]
