"""Referential validators.

Validators for foreign key relationships, orphan detection, and hierarchy integrity.

Import path in truthound: `from truthound.validators.referential import *`
"""

from .base import (
    ParameterDefinition,
    ParameterType,
    ValidatorCategory,
    ValidatorDefinition,
)

REFERENTIAL_VALIDATORS: list[ValidatorDefinition] = [
    ValidatorDefinition(
        name="ForeignKey",
        display_name="Foreign Key",
        category=ValidatorCategory.REFERENTIAL,
        description="Validates that all values in a column exist in a reference table's column.",
        parameters=[
            ParameterDefinition(
                name="column",
                label="Foreign Key Column",
                type=ParameterType.COLUMN,
                required=True,
                description="Column containing foreign key values",
            ),
            ParameterDefinition(
                name="reference_source",
                label="Reference Data Source",
                type=ParameterType.SOURCE_REF,
                required=True,
                description="Reference data source containing the primary key",
            ),
            ParameterDefinition(
                name="reference_column",
                label="Reference Column",
                type=ParameterType.STRING,
                required=True,
                description="Primary key column in the reference data",
            ),
        ],
        tags=["referential", "foreign_key", "fk", "relationship"],
        severity_default="high",
    ),
    ValidatorDefinition(
        name="CompositeForeignKey",
        display_name="Composite Foreign Key",
        category=ValidatorCategory.REFERENTIAL,
        description="Validates composite foreign key relationships across multiple columns.",
        parameters=[
            ParameterDefinition(
                name="columns",
                label="Foreign Key Columns",
                type=ParameterType.COLUMN_LIST,
                required=True,
                description="Columns forming the composite foreign key",
            ),
            ParameterDefinition(
                name="reference_source",
                label="Reference Data Source",
                type=ParameterType.SOURCE_REF,
                required=True,
                description="Reference data source containing the composite primary key",
            ),
            ParameterDefinition(
                name="reference_columns",
                label="Reference Columns",
                type=ParameterType.STRING_LIST,
                required=True,
                description="Columns forming the composite primary key in reference",
            ),
        ],
        tags=["referential", "composite_key", "foreign_key", "relationship"],
        severity_default="high",
    ),
    ValidatorDefinition(
        name="SelfReferentialFK",
        display_name="Self-Referential Foreign Key",
        category=ValidatorCategory.REFERENTIAL,
        description="Validates self-referential foreign keys (e.g., parent_id references id in same table).",
        parameters=[
            ParameterDefinition(
                name="column",
                label="Foreign Key Column",
                type=ParameterType.COLUMN,
                required=True,
                description="Column containing self-referential foreign key (e.g., parent_id)",
            ),
            ParameterDefinition(
                name="reference_column",
                label="Primary Key Column",
                type=ParameterType.COLUMN,
                required=True,
                description="Primary key column being referenced (e.g., id)",
            ),
            ParameterDefinition(
                name="allow_null",
                label="Allow Null Values",
                type=ParameterType.BOOLEAN,
                default=True,
                description="Whether null values are allowed (root nodes)",
            ),
        ],
        tags=["referential", "self_referential", "hierarchy", "tree"],
        severity_default="high",
    ),
    ValidatorDefinition(
        name="OrphanRecord",
        display_name="Orphan Record Detection",
        category=ValidatorCategory.REFERENTIAL,
        description="Detects orphan records that reference non-existent parent records.",
        parameters=[
            ParameterDefinition(
                name="column",
                label="Foreign Key Column",
                type=ParameterType.COLUMN,
                required=True,
                description="Column containing foreign key values",
            ),
            ParameterDefinition(
                name="reference_source",
                label="Reference Data Source",
                type=ParameterType.SOURCE_REF,
                required=True,
                description="Parent data source",
            ),
            ParameterDefinition(
                name="reference_column",
                label="Reference Column",
                type=ParameterType.STRING,
                required=True,
                description="Primary key column in the parent data",
            ),
        ],
        tags=["referential", "orphan", "integrity", "dangling"],
        severity_default="high",
    ),
    ValidatorDefinition(
        name="DanglingReference",
        display_name="Dangling Reference Detection",
        category=ValidatorCategory.REFERENTIAL,
        description="Detects references pointing to deleted or non-existent records.",
        parameters=[
            ParameterDefinition(
                name="column",
                label="Reference Column",
                type=ParameterType.COLUMN,
                required=True,
                description="Column containing reference values",
            ),
            ParameterDefinition(
                name="reference_source",
                label="Reference Data Source",
                type=ParameterType.SOURCE_REF,
                required=True,
                description="Target data source",
            ),
            ParameterDefinition(
                name="reference_column",
                label="Target Column",
                type=ParameterType.STRING,
                required=True,
                description="Column in target data being referenced",
            ),
        ],
        tags=["referential", "dangling", "broken_link", "integrity"],
        severity_default="high",
    ),
    ValidatorDefinition(
        name="CircularReference",
        display_name="Circular Reference Detection",
        category=ValidatorCategory.REFERENTIAL,
        description="Detects circular references in self-referential data (e.g., A→B→C→A).",
        parameters=[
            ParameterDefinition(
                name="id_column",
                label="ID Column",
                type=ParameterType.COLUMN,
                required=True,
                description="Primary key column (e.g., id)",
            ),
            ParameterDefinition(
                name="parent_column",
                label="Parent Column",
                type=ParameterType.COLUMN,
                required=True,
                description="Column referencing parent (e.g., parent_id)",
            ),
            ParameterDefinition(
                name="max_depth",
                label="Maximum Detection Depth",
                type=ParameterType.INTEGER,
                default=100,
                min_value=1,
                max_value=1000,
                description="Maximum depth to search for cycles",
            ),
        ],
        tags=["referential", "circular", "cycle", "hierarchy"],
        severity_default="critical",
    ),
    ValidatorDefinition(
        name="HierarchyDepth",
        display_name="Hierarchy Depth Validation",
        category=ValidatorCategory.REFERENTIAL,
        description="Validates that hierarchy depth doesn't exceed a maximum limit.",
        parameters=[
            ParameterDefinition(
                name="id_column",
                label="ID Column",
                type=ParameterType.COLUMN,
                required=True,
                description="Primary key column",
            ),
            ParameterDefinition(
                name="parent_column",
                label="Parent Column",
                type=ParameterType.COLUMN,
                required=True,
                description="Column referencing parent",
            ),
            ParameterDefinition(
                name="max_depth",
                label="Maximum Allowed Depth",
                type=ParameterType.INTEGER,
                required=True,
                min_value=1,
                max_value=100,
                description="Maximum allowed hierarchy depth",
            ),
        ],
        tags=["referential", "hierarchy", "depth", "tree"],
        severity_default="medium",
    ),
    ValidatorDefinition(
        name="CascadeIntegrity",
        display_name="Cascade Integrity",
        category=ValidatorCategory.REFERENTIAL,
        description="Validates cascade delete/update integrity across related tables.",
        parameters=[
            ParameterDefinition(
                name="column",
                label="Foreign Key Column",
                type=ParameterType.COLUMN,
                required=True,
                description="Column with cascade relationship",
            ),
            ParameterDefinition(
                name="reference_source",
                label="Reference Data Source",
                type=ParameterType.SOURCE_REF,
                required=True,
                description="Parent data source",
            ),
            ParameterDefinition(
                name="reference_column",
                label="Reference Column",
                type=ParameterType.STRING,
                required=True,
                description="Primary key in parent",
            ),
            ParameterDefinition(
                name="action",
                label="Cascade Action",
                type=ParameterType.SELECT,
                options=[
                    {"value": "cascade", "label": "Cascade"},
                    {"value": "set_null", "label": "Set Null"},
                    {"value": "restrict", "label": "Restrict"},
                    {"value": "no_action", "label": "No Action"},
                ],
                default="cascade",
                description="Expected cascade behavior",
            ),
        ],
        tags=["referential", "cascade", "delete", "update"],
        severity_default="high",
    ),
    ValidatorDefinition(
        name="MultiTableOrphan",
        display_name="Multi-Table Orphan Check",
        category=ValidatorCategory.REFERENTIAL,
        description="Detects orphan records across multiple related tables.",
        parameters=[
            ParameterDefinition(
                name="column",
                label="Foreign Key Column",
                type=ParameterType.COLUMN,
                required=True,
                description="Column containing foreign key",
            ),
            ParameterDefinition(
                name="reference_sources",
                label="Reference Data Sources",
                type=ParameterType.STRING_LIST,
                required=True,
                description="List of parent data source IDs",
            ),
            ParameterDefinition(
                name="reference_columns",
                label="Reference Columns",
                type=ParameterType.STRING_LIST,
                required=True,
                description="Corresponding primary key columns",
            ),
        ],
        tags=["referential", "orphan", "multi_table", "integrity"],
        severity_default="high",
    ),
]
