"""String validators.

Validators for pattern matching, format validation, and text content.
"""

from .base import (
    ParameterDefinition,
    ParameterType,
    ValidatorCategory,
    ValidatorDefinition,
)

STRING_VALIDATORS: list[ValidatorDefinition] = [
    ValidatorDefinition(
        name="Regex",
        display_name="Regex Pattern",
        category=ValidatorCategory.STRING,
        description="Validates strings against a regular expression pattern.",
        parameters=[
            ParameterDefinition(
                name="column",
                label="Column",
                type=ParameterType.COLUMN,
                required=True,
            ),
            ParameterDefinition(
                name="pattern",
                label="Regex Pattern",
                type=ParameterType.REGEX,
                description="Regular expression pattern",
                required=True,
                placeholder=r"^[A-Z]{2,3}-\d{4}$",
            ),
            ParameterDefinition(
                name="mostly",
                label="Mostly (Threshold)",
                type=ParameterType.FLOAT,
                min_value=0,
                max_value=1,
            ),
        ],
        tags=["string", "regex", "pattern"],
        severity_default="medium",
    ),
    ValidatorDefinition(
        name="RegexList",
        display_name="Regex List",
        category=ValidatorCategory.STRING,
        description="Validates against multiple regex patterns (any match passes).",
        parameters=[
            ParameterDefinition(
                name="column",
                label="Column",
                type=ParameterType.COLUMN,
                required=True,
            ),
            ParameterDefinition(
                name="patterns",
                label="Patterns",
                type=ParameterType.STRING_LIST,
                description="List of regex patterns (any match is valid)",
                required=True,
            ),
        ],
        tags=["string", "regex", "pattern", "list"],
        severity_default="medium",
    ),
    ValidatorDefinition(
        name="NotMatchRegex",
        display_name="Not Match Regex",
        category=ValidatorCategory.STRING,
        description="Ensures values do not match a specified pattern.",
        parameters=[
            ParameterDefinition(
                name="column",
                label="Column",
                type=ParameterType.COLUMN,
                required=True,
            ),
            ParameterDefinition(
                name="pattern",
                label="Forbidden Pattern",
                type=ParameterType.REGEX,
                required=True,
            ),
        ],
        tags=["string", "regex", "forbidden"],
        severity_default="high",
    ),
    ValidatorDefinition(
        name="Length",
        display_name="String Length",
        category=ValidatorCategory.STRING,
        description="Validates string length constraints.",
        parameters=[
            ParameterDefinition(
                name="column",
                label="Column",
                type=ParameterType.COLUMN,
                required=True,
            ),
            ParameterDefinition(
                name="min_length",
                label="Minimum Length",
                type=ParameterType.INTEGER,
                min_value=0,
            ),
            ParameterDefinition(
                name="max_length",
                label="Maximum Length",
                type=ParameterType.INTEGER,
                min_value=0,
            ),
        ],
        tags=["string", "length", "size"],
        severity_default="medium",
    ),
    ValidatorDefinition(
        name="Email",
        display_name="Email Format",
        category=ValidatorCategory.STRING,
        description="Validates email address format using RFC 5322 patterns.",
        parameters=[
            ParameterDefinition(
                name="column",
                label="Column",
                type=ParameterType.COLUMN,
                required=True,
            ),
        ],
        tags=["string", "email", "format"],
        severity_default="medium",
    ),
    ValidatorDefinition(
        name="Url",
        display_name="URL Format",
        category=ValidatorCategory.STRING,
        description="Validates URL format.",
        parameters=[
            ParameterDefinition(
                name="column",
                label="Column",
                type=ParameterType.COLUMN,
                required=True,
            ),
        ],
        tags=["string", "url", "format"],
        severity_default="medium",
    ),
    ValidatorDefinition(
        name="Phone",
        display_name="Phone Number",
        category=ValidatorCategory.STRING,
        description="Validates phone number format with international support.",
        parameters=[
            ParameterDefinition(
                name="column",
                label="Column",
                type=ParameterType.COLUMN,
                required=True,
            ),
            ParameterDefinition(
                name="country_code",
                label="Country Code",
                type=ParameterType.STRING,
                description="Expected country code (e.g., 'US', 'KR')",
                placeholder="US",
            ),
        ],
        tags=["string", "phone", "format"],
        severity_default="medium",
    ),
    ValidatorDefinition(
        name="Uuid",
        display_name="UUID Format",
        category=ValidatorCategory.STRING,
        description="Validates UUID format (versions 1-5).",
        parameters=[
            ParameterDefinition(
                name="column",
                label="Column",
                type=ParameterType.COLUMN,
                required=True,
            ),
        ],
        tags=["string", "uuid", "format"],
        severity_default="medium",
    ),
    ValidatorDefinition(
        name="IpAddress",
        display_name="IP Address",
        category=ValidatorCategory.STRING,
        description="Validates IPv4 and IPv6 address formats.",
        parameters=[
            ParameterDefinition(
                name="column",
                label="Column",
                type=ParameterType.COLUMN,
                required=True,
            ),
            ParameterDefinition(
                name="version",
                label="IP Version",
                type=ParameterType.SELECT,
                description="IP version to validate",
                options=[
                    {"value": "", "label": "Any (IPv4 or IPv6)"},
                    {"value": "4", "label": "IPv4 only"},
                    {"value": "6", "label": "IPv6 only"},
                ],
            ),
        ],
        tags=["string", "ip", "network", "format"],
        severity_default="medium",
    ),
    ValidatorDefinition(
        name="Format",
        display_name="Common Format",
        category=ValidatorCategory.STRING,
        description="Validates common format types.",
        parameters=[
            ParameterDefinition(
                name="column",
                label="Column",
                type=ParameterType.COLUMN,
                required=True,
            ),
            ParameterDefinition(
                name="format_type",
                label="Format Type",
                type=ParameterType.SELECT,
                required=True,
                options=[
                    {"value": "email", "label": "Email"},
                    {"value": "url", "label": "URL"},
                    {"value": "phone", "label": "Phone"},
                    {"value": "uuid", "label": "UUID"},
                    {"value": "ipv4", "label": "IPv4"},
                    {"value": "ipv6", "label": "IPv6"},
                    {"value": "credit_card", "label": "Credit Card"},
                    {"value": "ssn", "label": "SSN"},
                ],
            ),
        ],
        tags=["string", "format"],
        severity_default="medium",
    ),
    ValidatorDefinition(
        name="JsonParseable",
        display_name="JSON Parseable",
        category=ValidatorCategory.STRING,
        description="Ensures string values are valid JSON.",
        parameters=[
            ParameterDefinition(
                name="column",
                label="Column",
                type=ParameterType.COLUMN,
                required=True,
            ),
        ],
        tags=["string", "json", "format"],
        severity_default="medium",
    ),
    ValidatorDefinition(
        name="JsonSchema",
        display_name="JSON Schema",
        category=ValidatorCategory.STRING,
        description="Validates JSON strings against a JSON Schema.",
        parameters=[
            ParameterDefinition(
                name="column",
                label="Column",
                type=ParameterType.COLUMN,
                required=True,
            ),
            ParameterDefinition(
                name="schema",
                label="JSON Schema",
                type=ParameterType.SCHEMA,
                description="JSON Schema specification",
                required=True,
            ),
        ],
        tags=["string", "json", "schema"],
        severity_default="medium",
    ),
    ValidatorDefinition(
        name="Alphanumeric",
        display_name="Alphanumeric",
        category=ValidatorCategory.STRING,
        description="Ensures values contain only alphanumeric characters.",
        parameters=[
            ParameterDefinition(
                name="column",
                label="Column",
                type=ParameterType.COLUMN,
                required=True,
            ),
        ],
        tags=["string", "alphanumeric", "characters"],
        severity_default="low",
    ),
    ValidatorDefinition(
        name="ConsistentCasing",
        display_name="Consistent Casing",
        category=ValidatorCategory.STRING,
        description="Validates consistent casing patterns.",
        parameters=[
            ParameterDefinition(
                name="column",
                label="Column",
                type=ParameterType.COLUMN,
                required=True,
            ),
            ParameterDefinition(
                name="casing",
                label="Casing Style",
                type=ParameterType.SELECT,
                required=True,
                options=[
                    {"value": "lower", "label": "lowercase"},
                    {"value": "upper", "label": "UPPERCASE"},
                    {"value": "title", "label": "Title Case"},
                    {"value": "snake", "label": "snake_case"},
                    {"value": "camel", "label": "camelCase"},
                    {"value": "pascal", "label": "PascalCase"},
                    {"value": "kebab", "label": "kebab-case"},
                ],
            ),
        ],
        tags=["string", "casing", "style"],
        severity_default="low",
    ),
    ValidatorDefinition(
        name="LikePattern",
        display_name="LIKE Pattern",
        category=ValidatorCategory.STRING,
        description="SQL LIKE pattern matching with % and _ wildcards.",
        parameters=[
            ParameterDefinition(
                name="column",
                label="Column",
                type=ParameterType.COLUMN,
                required=True,
            ),
            ParameterDefinition(
                name="pattern",
                label="LIKE Pattern",
                type=ParameterType.STRING,
                description="SQL LIKE pattern (use % for any, _ for single char)",
                required=True,
                placeholder="PRD-%",
            ),
        ],
        tags=["string", "like", "sql", "pattern"],
        severity_default="medium",
    ),
    ValidatorDefinition(
        name="NotLikePattern",
        display_name="Not LIKE Pattern",
        category=ValidatorCategory.STRING,
        description="Ensures values do not match a LIKE pattern.",
        parameters=[
            ParameterDefinition(
                name="column",
                label="Column",
                type=ParameterType.COLUMN,
                required=True,
            ),
            ParameterDefinition(
                name="pattern",
                label="Forbidden LIKE Pattern",
                type=ParameterType.STRING,
                required=True,
            ),
        ],
        tags=["string", "like", "forbidden"],
        severity_default="high",
    ),
    ValidatorDefinition(
        name="DateutilParseable",
        display_name="Date Parseable",
        category=ValidatorCategory.STRING,
        description="Validates that strings can be parsed as dates.",
        parameters=[
            ParameterDefinition(
                name="column",
                label="Column",
                type=ParameterType.COLUMN,
                required=True,
            ),
        ],
        tags=["string", "date", "parseable"],
        severity_default="medium",
    ),
]
