"""Table validators.

Validators for table-level metadata, dimensions, freshness, and structure.
"""

from .base import (
    ParameterDefinition,
    ParameterType,
    ValidatorCategory,
    ValidatorDefinition,
)

TABLE_VALIDATORS: list[ValidatorDefinition] = [
    ValidatorDefinition(
        name="TableNotEmpty",
        display_name="Table Not Empty",
        category=ValidatorCategory.TABLE,
        description="Ensures the table contains at least one row.",
        parameters=[],
        tags=["table", "empty", "rows"],
        severity_default="critical",
    ),
    ValidatorDefinition(
        name="TableRowCountRange",
        display_name="Table Row Count Range",
        category=ValidatorCategory.TABLE,
        description="Validates that row count falls within a range.",
        parameters=[
            ParameterDefinition(
                name="min_rows",
                label="Minimum Rows",
                type=ParameterType.INTEGER,
                min_value=0,
            ),
            ParameterDefinition(
                name="max_rows",
                label="Maximum Rows",
                type=ParameterType.INTEGER,
                min_value=0,
            ),
        ],
        tags=["table", "row_count", "range"],
        severity_default="medium",
    ),
    ValidatorDefinition(
        name="TableRowCountExact",
        display_name="Table Row Count Exact",
        category=ValidatorCategory.TABLE,
        description="Validates exact row count with tolerance.",
        parameters=[
            ParameterDefinition(
                name="expected_rows",
                label="Expected Rows",
                type=ParameterType.INTEGER,
                required=True,
                min_value=0,
            ),
            ParameterDefinition(
                name="tolerance",
                label="Tolerance",
                type=ParameterType.INTEGER,
                description="Acceptable deviation from expected",
                default=0,
                min_value=0,
            ),
        ],
        tags=["table", "row_count", "exact"],
        severity_default="medium",
    ),
    ValidatorDefinition(
        name="TableColumnCount",
        display_name="Table Column Count",
        category=ValidatorCategory.TABLE,
        description="Validates the number of columns.",
        parameters=[
            ParameterDefinition(
                name="expected_count",
                label="Expected Count",
                type=ParameterType.INTEGER,
                min_value=0,
            ),
            ParameterDefinition(
                name="min_count",
                label="Minimum Count",
                type=ParameterType.INTEGER,
                min_value=0,
            ),
            ParameterDefinition(
                name="max_count",
                label="Maximum Count",
                type=ParameterType.INTEGER,
                min_value=0,
            ),
        ],
        tags=["table", "column_count"],
        severity_default="medium",
    ),
    ValidatorDefinition(
        name="TableRequiredColumns",
        display_name="Table Required Columns",
        category=ValidatorCategory.TABLE,
        description="Validates presence of required columns.",
        parameters=[
            ParameterDefinition(
                name="required_columns",
                label="Required Columns",
                type=ParameterType.STRING_LIST,
                required=True,
            ),
        ],
        tags=["table", "columns", "required"],
        severity_default="critical",
    ),
    ValidatorDefinition(
        name="TableForbiddenColumns",
        display_name="Table Forbidden Columns",
        category=ValidatorCategory.TABLE,
        description="Ensures certain columns are absent.",
        parameters=[
            ParameterDefinition(
                name="forbidden_columns",
                label="Forbidden Columns",
                type=ParameterType.STRING_LIST,
                required=True,
            ),
        ],
        tags=["table", "columns", "forbidden", "security"],
        severity_default="high",
    ),
    ValidatorDefinition(
        name="TableFreshness",
        display_name="Table Freshness",
        category=ValidatorCategory.TABLE,
        description="Validates that the table contains recent data.",
        parameters=[
            ParameterDefinition(
                name="datetime_column",
                label="Datetime Column",
                type=ParameterType.COLUMN,
                required=True,
            ),
            ParameterDefinition(
                name="max_age_hours",
                label="Max Age (Hours)",
                type=ParameterType.INTEGER,
                description="Maximum age of most recent record",
                required=True,
                min_value=1,
            ),
        ],
        tags=["table", "freshness", "recent"],
        severity_default="high",
    ),
    ValidatorDefinition(
        name="TableDataRecency",
        display_name="Table Data Recency",
        category=ValidatorCategory.TABLE,
        description="Ensures data is not older than specified days.",
        parameters=[
            ParameterDefinition(
                name="datetime_column",
                label="Datetime Column",
                type=ParameterType.COLUMN,
                required=True,
            ),
            ParameterDefinition(
                name="max_age_days",
                label="Max Age (Days)",
                type=ParameterType.INTEGER,
                required=True,
                min_value=1,
            ),
        ],
        tags=["table", "recency", "age"],
        severity_default="medium",
    ),
    ValidatorDefinition(
        name="TableUpdateFrequency",
        display_name="Table Update Frequency",
        category=ValidatorCategory.TABLE,
        description="Validates expected data update frequency.",
        parameters=[
            ParameterDefinition(
                name="datetime_column",
                label="Datetime Column",
                type=ParameterType.COLUMN,
                required=True,
            ),
            ParameterDefinition(
                name="expected_frequency",
                label="Expected Frequency",
                type=ParameterType.SELECT,
                required=True,
                options=[
                    {"value": "hourly", "label": "Hourly"},
                    {"value": "daily", "label": "Daily"},
                    {"value": "weekly", "label": "Weekly"},
                    {"value": "monthly", "label": "Monthly"},
                ],
            ),
            ParameterDefinition(
                name="tolerance_periods",
                label="Tolerance Periods",
                type=ParameterType.INTEGER,
                description="Number of periods allowed to miss",
                default=1,
                min_value=0,
            ),
        ],
        tags=["table", "frequency", "schedule"],
        severity_default="medium",
    ),
    ValidatorDefinition(
        name="TableSchemaMatch",
        display_name="Table Schema Match",
        category=ValidatorCategory.TABLE,
        description="Validates schema matches expected definition.",
        parameters=[
            ParameterDefinition(
                name="expected_schema",
                label="Expected Schema",
                type=ParameterType.SCHEMA,
                description="Expected schema as JSON {column: type}",
                required=True,
            ),
            ParameterDefinition(
                name="strict",
                label="Strict Mode",
                type=ParameterType.BOOLEAN,
                description="Reject extra columns not in schema",
                default=False,
            ),
        ],
        tags=["table", "schema", "match"],
        severity_default="high",
    ),
    ValidatorDefinition(
        name="TableColumnTypes",
        display_name="Table Column Types",
        category=ValidatorCategory.TABLE,
        description="Validates expected column data types.",
        parameters=[
            ParameterDefinition(
                name="expected_types",
                label="Expected Types",
                type=ParameterType.SCHEMA,
                description="JSON mapping of column names to expected types",
                required=True,
                placeholder='{"id": "Int64", "name": "String"}',
            ),
        ],
        tags=["table", "types", "columns"],
        severity_default="high",
    ),
    ValidatorDefinition(
        name="TableMemorySize",
        display_name="Table Memory Size",
        category=ValidatorCategory.TABLE,
        description="Validates estimated memory usage.",
        parameters=[
            ParameterDefinition(
                name="min_size_mb",
                label="Minimum Size (MB)",
                type=ParameterType.FLOAT,
                min_value=0,
            ),
            ParameterDefinition(
                name="max_size_mb",
                label="Maximum Size (MB)",
                type=ParameterType.FLOAT,
                min_value=0,
            ),
        ],
        tags=["table", "memory", "size"],
        severity_default="low",
    ),
    ValidatorDefinition(
        name="TableDimensions",
        display_name="Table Dimensions",
        category=ValidatorCategory.TABLE,
        description="Validates table dimensions (rows and columns).",
        parameters=[
            ParameterDefinition(
                name="min_rows",
                label="Minimum Rows",
                type=ParameterType.INTEGER,
                min_value=0,
            ),
            ParameterDefinition(
                name="max_rows",
                label="Maximum Rows",
                type=ParameterType.INTEGER,
                min_value=0,
            ),
            ParameterDefinition(
                name="min_cols",
                label="Minimum Columns",
                type=ParameterType.INTEGER,
                min_value=0,
            ),
            ParameterDefinition(
                name="max_cols",
                label="Maximum Columns",
                type=ParameterType.INTEGER,
                min_value=0,
            ),
        ],
        tags=["table", "dimensions", "size"],
        severity_default="medium",
    ),
    ValidatorDefinition(
        name="TableRowToColumnRatio",
        display_name="Row to Column Ratio",
        category=ValidatorCategory.TABLE,
        description="Validates the ratio of rows to columns.",
        parameters=[
            ParameterDefinition(
                name="min_ratio",
                label="Minimum Ratio",
                type=ParameterType.FLOAT,
                min_value=0,
            ),
            ParameterDefinition(
                name="max_ratio",
                label="Maximum Ratio",
                type=ParameterType.FLOAT,
                min_value=0,
            ),
        ],
        tags=["table", "ratio", "dimensions"],
        severity_default="low",
    ),
    ValidatorDefinition(
        name="TablePartitionCoverage",
        display_name="Table Partition Coverage",
        category=ValidatorCategory.TABLE,
        description="Validates data coverage across partitions.",
        parameters=[
            ParameterDefinition(
                name="partition_column",
                label="Partition Column",
                type=ParameterType.COLUMN,
                required=True,
            ),
            ParameterDefinition(
                name="expected_partitions",
                label="Expected Partitions",
                type=ParameterType.STRING_LIST,
                description="List of expected partition values",
            ),
            ParameterDefinition(
                name="min_rows_per_partition",
                label="Min Rows Per Partition",
                type=ParameterType.INTEGER,
                default=1,
                min_value=0,
            ),
        ],
        tags=["table", "partition", "coverage"],
        severity_default="medium",
    ),
    ValidatorDefinition(
        name="TableNullRatio",
        display_name="Table Null Ratio",
        category=ValidatorCategory.TABLE,
        description="Validates overall null ratio across the table.",
        parameters=[
            ParameterDefinition(
                name="max_null_ratio",
                label="Max Null Ratio",
                type=ParameterType.FLOAT,
                description="Maximum acceptable null ratio (0.0-1.0)",
                default=0.1,
                min_value=0,
                max_value=1,
            ),
            ParameterDefinition(
                name="columns",
                label="Columns",
                type=ParameterType.COLUMN_LIST,
                description="Columns to check (leave empty for all)",
            ),
        ],
        tags=["table", "null", "completeness"],
        severity_default="medium",
    ),
    ValidatorDefinition(
        name="TableDuplicateRatio",
        display_name="Table Duplicate Ratio",
        category=ValidatorCategory.TABLE,
        description="Validates overall duplicate row ratio.",
        parameters=[
            ParameterDefinition(
                name="max_duplicate_ratio",
                label="Max Duplicate Ratio",
                type=ParameterType.FLOAT,
                description="Maximum acceptable duplicate ratio",
                default=0.01,
                min_value=0,
                max_value=1,
            ),
            ParameterDefinition(
                name="columns",
                label="Columns",
                type=ParameterType.COLUMN_LIST,
                description="Columns to consider for duplicates (leave empty for all)",
            ),
        ],
        tags=["table", "duplicate", "uniqueness"],
        severity_default="medium",
    ),
]
