"""Time series validators.

Validators for time series data properties including gaps, monotonicity,
seasonality, and trend analysis.

Import path in truthound: `from truthound.validators.timeseries import *`
"""

from .base import (
    ParameterDefinition,
    ParameterType,
    ValidatorCategory,
    ValidatorDefinition,
)

TIMESERIES_VALIDATORS: list[ValidatorDefinition] = [
    ValidatorDefinition(
        name="TimeSeriesGap",
        display_name="Time Series Gap Detection",
        category=ValidatorCategory.TIMESERIES,
        description="Detects unexpected gaps in time series data.",
        parameters=[
            ParameterDefinition(
                name="timestamp_column",
                label="Timestamp Column",
                type=ParameterType.COLUMN,
                required=True,
                description="Column containing timestamps",
            ),
            ParameterDefinition(
                name="expected_interval",
                label="Expected Interval",
                type=ParameterType.STRING,
                required=True,
                description="Expected time interval (e.g., '1h', '1d', '5m')",
                placeholder="1h",
            ),
            ParameterDefinition(
                name="tolerance",
                label="Tolerance",
                type=ParameterType.FLOAT,
                default=0.1,
                min_value=0,
                max_value=1,
                description="Tolerance ratio for interval variation (0-1)",
            ),
        ],
        tags=["timeseries", "gap", "missing", "interval"],
        severity_default="high",
    ),
    ValidatorDefinition(
        name="TimeSeriesInterval",
        display_name="Time Series Interval Regularity",
        category=ValidatorCategory.TIMESERIES,
        description="Validates that time series has regular intervals.",
        parameters=[
            ParameterDefinition(
                name="timestamp_column",
                label="Timestamp Column",
                type=ParameterType.COLUMN,
                required=True,
                description="Column containing timestamps",
            ),
            ParameterDefinition(
                name="interval",
                label="Expected Interval",
                type=ParameterType.STRING,
                required=True,
                description="Expected time interval (e.g., '1h', '1d', '5m')",
            ),
            ParameterDefinition(
                name="strict",
                label="Strict Mode",
                type=ParameterType.BOOLEAN,
                default=False,
                description="If true, all intervals must match exactly",
            ),
        ],
        tags=["timeseries", "interval", "regularity", "frequency"],
        severity_default="medium",
    ),
    ValidatorDefinition(
        name="TimeSeriesDuplicate",
        display_name="Time Series Duplicate Timestamp",
        category=ValidatorCategory.TIMESERIES,
        description="Detects duplicate timestamps in time series data.",
        parameters=[
            ParameterDefinition(
                name="timestamp_column",
                label="Timestamp Column",
                type=ParameterType.COLUMN,
                required=True,
                description="Column containing timestamps",
            ),
            ParameterDefinition(
                name="group_columns",
                label="Group Columns",
                type=ParameterType.COLUMN_LIST,
                description="Additional columns to group by (for multi-series data)",
            ),
        ],
        tags=["timeseries", "duplicate", "timestamp", "unique"],
        severity_default="high",
    ),
    ValidatorDefinition(
        name="TimeSeriesMonotonic",
        display_name="Time Series Monotonicity",
        category=ValidatorCategory.TIMESERIES,
        description="Validates that timestamps are strictly monotonic (always increasing).",
        parameters=[
            ParameterDefinition(
                name="timestamp_column",
                label="Timestamp Column",
                type=ParameterType.COLUMN,
                required=True,
                description="Column containing timestamps",
            ),
            ParameterDefinition(
                name="direction",
                label="Direction",
                type=ParameterType.SELECT,
                options=[
                    {"value": "increasing", "label": "Increasing"},
                    {"value": "decreasing", "label": "Decreasing"},
                ],
                default="increasing",
                description="Expected monotonicity direction",
            ),
            ParameterDefinition(
                name="strict",
                label="Strictly Monotonic",
                type=ParameterType.BOOLEAN,
                default=True,
                description="If true, no equal consecutive values allowed",
            ),
        ],
        tags=["timeseries", "monotonic", "order", "sequence"],
        severity_default="high",
    ),
    ValidatorDefinition(
        name="TimeSeriesOrder",
        display_name="Time Series Order",
        category=ValidatorCategory.TIMESERIES,
        description="Validates that timestamps are in chronological order.",
        parameters=[
            ParameterDefinition(
                name="timestamp_column",
                label="Timestamp Column",
                type=ParameterType.COLUMN,
                required=True,
                description="Column containing timestamps",
            ),
            ParameterDefinition(
                name="allow_equal",
                label="Allow Equal Timestamps",
                type=ParameterType.BOOLEAN,
                default=False,
                description="Whether equal consecutive timestamps are allowed",
            ),
        ],
        tags=["timeseries", "order", "chronological", "sequence"],
        severity_default="medium",
    ),
    ValidatorDefinition(
        name="Seasonality",
        display_name="Seasonality Validation",
        category=ValidatorCategory.TIMESERIES,
        description="Validates expected seasonal patterns in time series data.",
        parameters=[
            ParameterDefinition(
                name="timestamp_column",
                label="Timestamp Column",
                type=ParameterType.COLUMN,
                required=True,
                description="Column containing timestamps",
            ),
            ParameterDefinition(
                name="value_column",
                label="Value Column",
                type=ParameterType.COLUMN,
                required=True,
                description="Column containing the time series values",
            ),
            ParameterDefinition(
                name="period",
                label="Seasonal Period",
                type=ParameterType.SELECT,
                options=[
                    {"value": "daily", "label": "Daily (24h)"},
                    {"value": "weekly", "label": "Weekly (7d)"},
                    {"value": "monthly", "label": "Monthly"},
                    {"value": "quarterly", "label": "Quarterly"},
                    {"value": "yearly", "label": "Yearly"},
                ],
                required=True,
                description="Expected seasonal period",
            ),
            ParameterDefinition(
                name="min_strength",
                label="Minimum Seasonality Strength",
                type=ParameterType.FLOAT,
                default=0.3,
                min_value=0,
                max_value=1,
                description="Minimum acceptable seasonality strength (0-1)",
            ),
        ],
        tags=["timeseries", "seasonality", "pattern", "periodic"],
        severity_default="medium",
    ),
    ValidatorDefinition(
        name="Trend",
        display_name="Trend Validation",
        category=ValidatorCategory.TIMESERIES,
        description="Validates expected trend direction in time series data.",
        parameters=[
            ParameterDefinition(
                name="timestamp_column",
                label="Timestamp Column",
                type=ParameterType.COLUMN,
                required=True,
                description="Column containing timestamps",
            ),
            ParameterDefinition(
                name="value_column",
                label="Value Column",
                type=ParameterType.COLUMN,
                required=True,
                description="Column containing the time series values",
            ),
            ParameterDefinition(
                name="expected_trend",
                label="Expected Trend",
                type=ParameterType.SELECT,
                options=[
                    {"value": "increasing", "label": "Increasing"},
                    {"value": "decreasing", "label": "Decreasing"},
                    {"value": "stable", "label": "Stable"},
                ],
                required=True,
                description="Expected trend direction",
            ),
            ParameterDefinition(
                name="significance",
                label="Significance Level",
                type=ParameterType.FLOAT,
                default=0.05,
                min_value=0.001,
                max_value=0.5,
                description="Statistical significance level for trend detection",
            ),
        ],
        tags=["timeseries", "trend", "direction", "growth"],
        severity_default="medium",
    ),
    ValidatorDefinition(
        name="TrendBreak",
        display_name="Trend Break Detection",
        category=ValidatorCategory.TIMESERIES,
        description="Detects unexpected trend breaks or structural changes in time series.",
        parameters=[
            ParameterDefinition(
                name="timestamp_column",
                label="Timestamp Column",
                type=ParameterType.COLUMN,
                required=True,
                description="Column containing timestamps",
            ),
            ParameterDefinition(
                name="value_column",
                label="Value Column",
                type=ParameterType.COLUMN,
                required=True,
                description="Column containing the time series values",
            ),
            ParameterDefinition(
                name="sensitivity",
                label="Sensitivity",
                type=ParameterType.FLOAT,
                default=0.5,
                min_value=0,
                max_value=1,
                description="Detection sensitivity (higher = more sensitive)",
            ),
        ],
        tags=["timeseries", "trend", "break", "change_point"],
        severity_default="medium",
    ),
    ValidatorDefinition(
        name="TimeSeriesCompleteness",
        display_name="Time Series Completeness",
        category=ValidatorCategory.TIMESERIES,
        description="Validates that time series covers the expected date range completely.",
        parameters=[
            ParameterDefinition(
                name="timestamp_column",
                label="Timestamp Column",
                type=ParameterType.COLUMN,
                required=True,
                description="Column containing timestamps",
            ),
            ParameterDefinition(
                name="start_date",
                label="Expected Start Date",
                type=ParameterType.DATE,
                description="Expected start date of the series",
            ),
            ParameterDefinition(
                name="end_date",
                label="Expected End Date",
                type=ParameterType.DATE,
                description="Expected end date of the series",
            ),
            ParameterDefinition(
                name="min_completeness",
                label="Minimum Completeness",
                type=ParameterType.FLOAT,
                default=0.95,
                min_value=0,
                max_value=1,
                description="Minimum required completeness ratio (0-1)",
            ),
        ],
        tags=["timeseries", "completeness", "coverage", "range"],
        severity_default="high",
    ),
    ValidatorDefinition(
        name="TimeSeriesDateRange",
        display_name="Time Series Date Range",
        category=ValidatorCategory.TIMESERIES,
        description="Validates that all timestamps fall within an expected date range.",
        parameters=[
            ParameterDefinition(
                name="timestamp_column",
                label="Timestamp Column",
                type=ParameterType.COLUMN,
                required=True,
                description="Column containing timestamps",
            ),
            ParameterDefinition(
                name="min_date",
                label="Minimum Date",
                type=ParameterType.DATE,
                description="Earliest acceptable date",
            ),
            ParameterDefinition(
                name="max_date",
                label="Maximum Date",
                type=ParameterType.DATE,
                description="Latest acceptable date",
            ),
        ],
        tags=["timeseries", "date_range", "bounds", "validation"],
        severity_default="medium",
    ),
    ValidatorDefinition(
        name="TimeSeriesValueCompleteness",
        display_name="Time Series Value Completeness",
        category=ValidatorCategory.TIMESERIES,
        description="Validates that values are present for all expected time points.",
        parameters=[
            ParameterDefinition(
                name="timestamp_column",
                label="Timestamp Column",
                type=ParameterType.COLUMN,
                required=True,
                description="Column containing timestamps",
            ),
            ParameterDefinition(
                name="value_column",
                label="Value Column",
                type=ParameterType.COLUMN,
                required=True,
                description="Column containing the time series values",
            ),
            ParameterDefinition(
                name="max_null_ratio",
                label="Maximum Null Ratio",
                type=ParameterType.FLOAT,
                default=0.05,
                min_value=0,
                max_value=1,
                description="Maximum acceptable ratio of null values",
            ),
        ],
        tags=["timeseries", "completeness", "null", "missing"],
        severity_default="medium",
    ),
]
