/* eslint-disable */
export default {
  "key": "driftMonitor",
  "content": {
    "nodeType": "translation",
    "translation": {
      "en": {
        "title": "Drift Monitoring",
        "subtitle": "Automatic drift detection with alerts",
        "tabs": {
          "monitors": "Monitors",
          "alerts": "Alerts",
          "trends": "Trends",
          "basic": "Basic",
          "performance": "Performance"
        },
        "monitor": {
          "createMonitor": "Create Monitor",
          "editMonitor": "Edit Monitor",
          "deleteMonitor": "Delete Monitor",
          "runNow": "Run Now",
          "pause": "Pause",
          "resume": "Resume",
          "name": "Monitor Name",
          "baselineSource": "Baseline Source",
          "currentSource": "Current Source",
          "schedule": "Schedule",
          "method": "Detection Method",
          "threshold": "Drift Threshold",
          "columns": "Columns to Monitor",
          "alertOnDrift": "Alert on Drift",
          "criticalThreshold": "Critical Alert Threshold",
          "highThreshold": "High Alert Threshold",
          "notificationChannels": "Notification Channels"
        },
        "status": {
          "active": "Active",
          "paused": "Paused",
          "error": "Error"
        },
        "severity": {
          "critical": "Critical",
          "high": "High",
          "medium": "Medium",
          "low": "Low"
        },
        "alertStatus": {
          "open": "Open",
          "acknowledged": "Acknowledged",
          "resolved": "Resolved",
          "ignored": "Ignored"
        },
        "alertActions": {
          "acknowledge": "Acknowledge",
          "resolve": "Resolve",
          "ignore": "Ignore",
          "addNote": "Add Note",
          "viewDetails": "View Details"
        },
        "stats": {
          "totalMonitors": "Total Monitors",
          "activeMonitors": "Active Monitors",
          "monitorsWithDrift": "With Drift",
          "openAlerts": "Open Alerts",
          "criticalAlerts": "Critical",
          "driftRate": "Drift Rate",
          "lastRun": "Last Run",
          "totalRuns": "Total Runs",
          "consecutiveDrift": "Consecutive Drift"
        },
        "schedulePresets": {
          "hourly": "Every Hour",
          "daily": "Daily",
          "weekly": "Weekly",
          "custom": "Custom"
        },
        "trend": {
          "title": "Drift Trend",
          "period": "Period",
          "last7Days": "Last 7 Days",
          "last30Days": "Last 30 Days",
          "last90Days": "Last 90 Days",
          "avgDrift": "Avg. Drift",
          "maxDrift": "Max Drift",
          "driftOccurrence": "Drift Occurrence"
        },
        "empty": {
          "noMonitors": "No drift monitors",
          "noMonitorsDesc": "Create a monitor to automatically detect drift between data sources",
          "noAlerts": "No alerts",
          "noAlertsDesc": "No drift alerts have been triggered",
          "noRunData": "No run data available",
          "runMonitorFirst": "Run the monitor to see column details"
        },
        "messages": {
          "monitorCreated": "Monitor created",
          "monitorUpdated": "Monitor updated",
          "monitorDeleted": "Monitor deleted",
          "monitorRunStarted": "Monitor run started",
          "alertAcknowledged": "Alert acknowledged",
          "alertResolved": "Alert resolved",
          "driftDetected": "Drift detected!",
          "noDriftDetected": "No drift detected"
        },
        "confirm": {
          "deleteMonitor": "Are you sure you want to delete this monitor?",
          "pauseMonitor": "Are you sure you want to pause this monitor?"
        },
        "table": {
          "name": "Name",
          "sources": "Sources",
          "schedule": "Schedule",
          "status": "Status",
          "lastRun": "Last Run",
          "driftStatus": "Drift Status",
          "actions": "Actions",
          "severity": "Severity",
          "message": "Message",
          "alertTime": "Alert Time"
        },
        "columnDrilldown": {
          "title": "Column Drift Analysis",
          "totalColumns": "columns",
          "drifted": "drifted",
          "selectColumn": "Select a column to view details",
          "noResults": "No columns match the filter criteria",
          "searchPlaceholder": "Search columns...",
          "viewDetails": "View Column Details",
          "distribution": "Distribution Comparison",
          "baseline": "Baseline",
          "current": "Current",
          "overlay": "Overlay",
          "smooth": "Smooth",
          "tabs": {
            "distribution": "Distribution",
            "statistics": "Statistics"
          },
          "filter": {
            "all": "All Columns",
            "drifted": "Drifted Only",
            "notDrifted": "Not Drifted",
            "high": "High Level",
            "medium": "Medium Level",
            "low": "Low Level"
          },
          "sort": {
            "drift": "By Drift",
            "level": "By Level",
            "pvalue": "By P-Value",
            "name": "By Name"
          },
          "levels": {
            "high": "High",
            "medium": "Medium",
            "low": "Low",
            "none": "None"
          },
          "testResults": "Statistical Test Results",
          "testMethod": "Test Method",
          "driftLevel": "Drift Level",
          "statistic": "Test Statistic",
          "pValue": "P-Value"
        },
        "columnStats": {
          "statistic": "Statistic",
          "baseline": "Baseline",
          "current": "Current",
          "change": "Change",
          "mean": "Mean",
          "std": "Std Dev",
          "median": "Median",
          "min": "Min",
          "max": "Max",
          "q25": "25th %ile",
          "q75": "75th %ile",
          "count": "Count",
          "nullCount": "Null Count",
          "uniqueCount": "Unique Count"
        },
        "preview": {
          "title": "Preview Drift",
          "previewDrift": "Preview Drift",
          "description": "Compare two data sources to preview drift results before creating a monitor",
          "runPreview": "Run Preview",
          "previewResults": "Preview Results",
          "reviewBeforeCreate": "Review drift results before creating the monitor",
          "backToConfig": "Back to Configuration",
          "sameSourceWarning": "Baseline and current source must be different",
          "driftStatus": "Drift Status",
          "driftDetected": "Drift Detected",
          "noDrift": "No Drift",
          "driftPercentage": "Drift Percentage",
          "columnsAffected": "columns affected",
          "rowComparison": "Row Count",
          "baseline": "Baseline",
          "current": "Current",
          "configuration": "Configuration",
          "mostAffected": "Most Affected Columns",
          "columnResults": "Column Results",
          "column": "Column",
          "type": "Type",
          "status": "Status",
          "level": "Level",
          "pValue": "P-Value",
          "statistic": "Statistic",
          "testStatistic": "Test Statistic",
          "distributionComparison": "Distribution Comparison"
        },
        "rootCause": {
          "title": "Root Cause Analysis",
          "subtitle": "Detailed analysis of why drift is occurring",
          "analyzeRootCause": "Analyze Root Cause",
          "noData": "No root cause data available",
          "noAnalysis": "No analysis available",
          "noDrift": "No drift detected in any columns",
          "totalColumns": "Total Columns",
          "driftedColumns": "Drifted Columns",
          "confidence": "Confidence",
          "analysisTime": "Analysis Time",
          "volumeChange": "Data Volume Change",
          "causeDistribution": "Cause Distribution",
          "columnAnalysis": "Column Analysis",
          "columnAnalysisDesc": "Detailed breakdown by column",
          "detectedCauses": "Detected Causes",
          "statisticalShifts": "Statistical Shifts",
          "causes": {
            "mean_shift": "Mean Shift",
            "variance_change": "Variance Change",
            "new_categories": "New Categories",
            "missing_categories": "Missing Categories",
            "outlier_introduction": "Outlier Introduction",
            "data_volume_change": "Data Volume Change",
            "temporal_pattern": "Temporal Pattern",
            "distribution_shape_change": "Distribution Shape Change",
            "null_rate_change": "Null Rate Change"
          },
          "remediations": "Suggested Actions",
          "remediationsDesc": "Recommended steps to address drift issues",
          "noRemediations": "No actions needed",
          "noRemediationsDesc": "No remediation suggestions at this time",
          "affectedColumns": "Affected Columns",
          "manualReview": "Requires manual review",
          "automationAvailable": "Automation available",
          "runAutomation": "Run Automation",
          "investigate": "Investigate",
          "dismiss": "Dismiss",
          "quickSummary": "Quick Summary",
          "totalSuggestions": "Total suggestions",
          "highPriority": "High priority",
          "automatable": "Automatable",
          "actions": {
            "investigate_upstream": "Investigate Upstream",
            "update_baseline": "Update Baseline",
            "adjust_threshold": "Adjust Threshold",
            "review_data_pipeline": "Review Data Pipeline",
            "check_data_source": "Check Data Source",
            "normalize_values": "Normalize Values",
            "filter_outliers": "Filter Outliers",
            "retrain_model": "Retrain Model",
            "acknowledge_expected_change": "Acknowledge Expected Change"
          }
        },
        "sampling": {
          "title": "Sampling Configuration",
          "description": "Enable sampling for faster processing of large datasets",
          "method": "Sampling Method",
          "sampleSize": "Sample Size",
          "confidenceLevel": "Confidence Level",
          "marginOfError": "Margin of Error",
          "strataColumn": "Stratification Column",
          "estimatedTime": "Est. Time",
          "speedup": "Speedup",
          "autoEstimate": "Auto-estimated",
          "advancedSettings": "Advanced Settings",
          "earlyStopThreshold": "Early Stop Threshold",
          "earlyStopDescription": "Stop processing when this percentage of columns show drift",
          "maxWorkers": "Max Parallel Workers",
          "largeDatasetNotice": "Large Dataset Detected",
          "largeDatasetDescription": "This dataset has {rows} rows. Sampling is recommended for optimal performance."
        },
        "largeDataset": {
          "title": "Large Dataset Warning",
          "rows": "rows",
          "description": "Processing this dataset without sampling may take a long time. We recommend enabling sampling for better performance.",
          "fullScan": "Full Scan",
          "withSampling": "With Sampling",
          "estimatedTime": "Estimated Time",
          "faster": "faster",
          "recommendations": "Recommendations",
          "recommendation1": "Enable sampling to process only a statistically significant subset",
          "recommendation2": "Use stratified sampling if you need to ensure category coverage",
          "recommendation3": "Consider increasing the threshold for faster processing",
          "enableSampling": "Enable Sampling",
          "enableSamplingShort": "Enable",
          "inlineWarning": "Dataset has {rows} rows. Sampling recommended."
        },
        "progress": {
          "running": "Processing...",
          "completed": "Completed",
          "cancelled": "Cancelled",
          "error": "Error",
          "progress": "Progress",
          "chunks": "Chunks",
          "rowsProcessed": "Rows Processed",
          "elapsed": "Elapsed",
          "eta": "ETA",
          "cancel": "Cancel",
          "earlyStopTriggered": "Early Stop Triggered",
          "earlyStopReason": "Sufficient drift detected to conclude analysis",
          "driftedColumnsFound": "Drifted Columns Found",
          "showDetails": "Show Details",
          "hideDetails": "Hide Details"
        }
      },
      "ko": {
        "title": "드리프트 모니터링",
        "subtitle": "알림과 함께하는 자동 드리프트 감지",
        "tabs": {
          "monitors": "모니터",
          "alerts": "알림",
          "trends": "트렌드",
          "basic": "기본",
          "performance": "성능"
        },
        "monitor": {
          "createMonitor": "모니터 생성",
          "editMonitor": "모니터 편집",
          "deleteMonitor": "모니터 삭제",
          "runNow": "지금 실행",
          "pause": "일시정지",
          "resume": "재개",
          "name": "모니터 이름",
          "baselineSource": "기준 소스",
          "currentSource": "현재 소스",
          "schedule": "스케줄",
          "method": "탐지 방법",
          "threshold": "드리프트 임계값",
          "columns": "모니터링할 컬럼",
          "alertOnDrift": "드리프트 시 알림",
          "criticalThreshold": "심각 알림 임계값",
          "highThreshold": "높음 알림 임계값",
          "notificationChannels": "알림 채널"
        },
        "status": {
          "active": "활성",
          "paused": "일시정지",
          "error": "오류"
        },
        "severity": {
          "critical": "심각",
          "high": "높음",
          "medium": "중간",
          "low": "낮음"
        },
        "alertStatus": {
          "open": "열림",
          "acknowledged": "확인됨",
          "resolved": "해결됨",
          "ignored": "무시됨"
        },
        "alertActions": {
          "acknowledge": "확인",
          "resolve": "해결",
          "ignore": "무시",
          "addNote": "메모 추가",
          "viewDetails": "상세 보기"
        },
        "stats": {
          "totalMonitors": "전체 모니터",
          "activeMonitors": "활성 모니터",
          "monitorsWithDrift": "드리프트 발생",
          "openAlerts": "미해결 알림",
          "criticalAlerts": "심각",
          "driftRate": "드리프트 비율",
          "lastRun": "마지막 실행",
          "totalRuns": "전체 실행",
          "consecutiveDrift": "연속 드리프트"
        },
        "schedulePresets": {
          "hourly": "매시간",
          "daily": "매일",
          "weekly": "매주",
          "custom": "사용자 정의"
        },
        "trend": {
          "title": "드리프트 트렌드",
          "period": "기간",
          "last7Days": "최근 7일",
          "last30Days": "최근 30일",
          "last90Days": "최근 90일",
          "avgDrift": "평균 드리프트",
          "maxDrift": "최대 드리프트",
          "driftOccurrence": "드리프트 발생률"
        },
        "empty": {
          "noMonitors": "드리프트 모니터 없음",
          "noMonitorsDesc": "데이터 소스 간 드리프트를 자동으로 감지하는 모니터를 생성하세요",
          "noAlerts": "알림 없음",
          "noAlertsDesc": "발생한 드리프트 알림이 없습니다",
          "noRunData": "실행 데이터 없음",
          "runMonitorFirst": "컬럼 상세 정보를 보려면 모니터를 실행하세요"
        },
        "messages": {
          "monitorCreated": "모니터가 생성되었습니다",
          "monitorUpdated": "모니터가 업데이트되었습니다",
          "monitorDeleted": "모니터가 삭제되었습니다",
          "monitorRunStarted": "모니터 실행이 시작되었습니다",
          "alertAcknowledged": "알림이 확인되었습니다",
          "alertResolved": "알림이 해결되었습니다",
          "driftDetected": "드리프트가 감지되었습니다!",
          "noDriftDetected": "드리프트가 감지되지 않았습니다"
        },
        "confirm": {
          "deleteMonitor": "이 모니터를 삭제하시겠습니까?",
          "pauseMonitor": "이 모니터를 일시정지하시겠습니까?"
        },
        "table": {
          "name": "이름",
          "sources": "소스",
          "schedule": "스케줄",
          "status": "상태",
          "lastRun": "마지막 실행",
          "driftStatus": "드리프트 상태",
          "actions": "작업",
          "severity": "심각도",
          "message": "메시지",
          "alertTime": "알림 시간"
        },
        "columnDrilldown": {
          "title": "컬럼 드리프트 분석",
          "totalColumns": "개 컬럼",
          "drifted": "드리프트",
          "selectColumn": "상세 정보를 보려면 컬럼을 선택하세요",
          "noResults": "필터 조건에 맞는 컬럼이 없습니다",
          "searchPlaceholder": "컬럼 검색...",
          "viewDetails": "컬럼 상세 보기",
          "distribution": "분포 비교",
          "baseline": "기준",
          "current": "현재",
          "overlay": "오버레이",
          "smooth": "스무딩",
          "tabs": {
            "distribution": "분포",
            "statistics": "통계"
          },
          "filter": {
            "all": "전체 컬럼",
            "drifted": "드리프트만",
            "notDrifted": "드리프트 없음",
            "high": "높음 수준",
            "medium": "중간 수준",
            "low": "낮음 수준"
          },
          "sort": {
            "drift": "드리프트순",
            "level": "수준순",
            "pvalue": "P값순",
            "name": "이름순"
          },
          "levels": {
            "high": "높음",
            "medium": "중간",
            "low": "낮음",
            "none": "없음"
          },
          "testResults": "통계 검정 결과",
          "testMethod": "검정 방법",
          "driftLevel": "드리프트 수준",
          "statistic": "검정 통계량",
          "pValue": "P값"
        },
        "columnStats": {
          "statistic": "통계",
          "baseline": "기준",
          "current": "현재",
          "change": "변화",
          "mean": "평균",
          "std": "표준편차",
          "median": "중앙값",
          "min": "최소값",
          "max": "최대값",
          "q25": "25 백분위",
          "q75": "75 백분위",
          "count": "건수",
          "nullCount": "Null 수",
          "uniqueCount": "고유값 수"
        },
        "preview": {
          "title": "드리프트 미리보기",
          "previewDrift": "드리프트 미리보기",
          "description": "모니터 생성 전 두 데이터 소스를 비교하여 드리프트 결과를 미리 확인하세요",
          "runPreview": "미리보기 실행",
          "previewResults": "미리보기 결과",
          "reviewBeforeCreate": "모니터 생성 전 드리프트 결과를 검토하세요",
          "backToConfig": "설정으로 돌아가기",
          "sameSourceWarning": "기준 소스와 현재 소스가 달라야 합니다",
          "driftStatus": "드리프트 상태",
          "driftDetected": "드리프트 감지됨",
          "noDrift": "드리프트 없음",
          "driftPercentage": "드리프트 비율",
          "columnsAffected": "개 컬럼 영향",
          "rowComparison": "행 수",
          "baseline": "기준",
          "current": "현재",
          "configuration": "설정",
          "mostAffected": "가장 영향받은 컬럼",
          "columnResults": "컬럼별 결과",
          "column": "컬럼",
          "type": "타입",
          "status": "상태",
          "level": "수준",
          "pValue": "P값",
          "statistic": "통계량",
          "testStatistic": "검정 통계량",
          "distributionComparison": "분포 비교"
        },
        "rootCause": {
          "title": "근본 원인 분석",
          "subtitle": "드리프트 발생 원인에 대한 상세 분석",
          "analyzeRootCause": "근본 원인 분석",
          "noData": "근본 원인 데이터 없음",
          "noAnalysis": "분석 결과 없음",
          "noDrift": "어떤 컬럼에서도 드리프트가 감지되지 않았습니다",
          "totalColumns": "전체 컬럼",
          "driftedColumns": "드리프트 컬럼",
          "confidence": "신뢰도",
          "analysisTime": "분석 시간",
          "volumeChange": "데이터 볼륨 변화",
          "causeDistribution": "원인 분포",
          "columnAnalysis": "컬럼 분석",
          "columnAnalysisDesc": "컬럼별 상세 분석",
          "detectedCauses": "감지된 원인",
          "statisticalShifts": "통계적 변화",
          "causes": {
            "mean_shift": "평균 변화",
            "variance_change": "분산 변화",
            "new_categories": "신규 카테고리",
            "missing_categories": "누락된 카테고리",
            "outlier_introduction": "이상치 유입",
            "data_volume_change": "데이터 볼륨 변화",
            "temporal_pattern": "시계열 패턴",
            "distribution_shape_change": "분포 형태 변화",
            "null_rate_change": "Null 비율 변화"
          },
          "remediations": "권장 조치",
          "remediationsDesc": "드리프트 문제 해결을 위한 권장 단계",
          "noRemediations": "조치 필요 없음",
          "noRemediationsDesc": "현재 권장 조치 사항이 없습니다",
          "affectedColumns": "영향받는 컬럼",
          "manualReview": "수동 검토 필요",
          "automationAvailable": "자동화 가능",
          "runAutomation": "자동화 실행",
          "investigate": "조사",
          "dismiss": "무시",
          "quickSummary": "빠른 요약",
          "totalSuggestions": "전체 제안",
          "highPriority": "높은 우선순위",
          "automatable": "자동화 가능",
          "actions": {
            "investigate_upstream": "업스트림 조사",
            "update_baseline": "기준 업데이트",
            "adjust_threshold": "임계값 조정",
            "review_data_pipeline": "데이터 파이프라인 검토",
            "check_data_source": "데이터 소스 확인",
            "normalize_values": "값 정규화",
            "filter_outliers": "이상치 필터링",
            "retrain_model": "모델 재학습",
            "acknowledge_expected_change": "예상된 변경 확인"
          }
        },
        "sampling": {
          "title": "샘플링 설정",
          "description": "대용량 데이터셋의 빠른 처리를 위해 샘플링을 활성화하세요",
          "method": "샘플링 방법",
          "sampleSize": "샘플 크기",
          "confidenceLevel": "신뢰 수준",
          "marginOfError": "오차 범위",
          "strataColumn": "계층화 컬럼",
          "estimatedTime": "예상 시간",
          "speedup": "속도 향상",
          "autoEstimate": "자동 추정",
          "advancedSettings": "고급 설정",
          "earlyStopThreshold": "조기 중단 임계값",
          "earlyStopDescription": "이 비율의 컬럼에서 드리프트가 감지되면 처리를 중단합니다",
          "maxWorkers": "최대 병렬 워커",
          "largeDatasetNotice": "대용량 데이터셋 감지됨",
          "largeDatasetDescription": "이 데이터셋은 {rows} 행을 포함합니다. 최적의 성능을 위해 샘플링을 권장합니다."
        },
        "largeDataset": {
          "title": "대용량 데이터셋 경고",
          "rows": "행",
          "description": "샘플링 없이 이 데이터셋을 처리하면 오랜 시간이 걸릴 수 있습니다. 더 나은 성능을 위해 샘플링을 활성화하는 것을 권장합니다.",
          "fullScan": "전체 스캔",
          "withSampling": "샘플링 사용",
          "estimatedTime": "예상 시간",
          "faster": "더 빠름",
          "recommendations": "권장 사항",
          "recommendation1": "통계적으로 유의미한 부분집합만 처리하도록 샘플링을 활성화하세요",
          "recommendation2": "카테고리 커버리지를 보장해야 한다면 계층화 샘플링을 사용하세요",
          "recommendation3": "더 빠른 처리를 위해 임계값을 높이는 것을 고려하세요",
          "enableSampling": "샘플링 활성화",
          "enableSamplingShort": "활성화",
          "inlineWarning": "데이터셋에 {rows} 행이 있습니다. 샘플링을 권장합니다."
        },
        "progress": {
          "running": "처리 중...",
          "completed": "완료됨",
          "cancelled": "취소됨",
          "error": "오류",
          "progress": "진행률",
          "chunks": "청크",
          "rowsProcessed": "처리된 행",
          "elapsed": "경과 시간",
          "eta": "남은 시간",
          "cancel": "취소",
          "earlyStopTriggered": "조기 중단 활성화됨",
          "earlyStopReason": "분석 결론을 내리기에 충분한 드리프트가 감지되었습니다",
          "driftedColumnsFound": "드리프트 컬럼 발견",
          "showDetails": "상세 보기",
          "hideDetails": "숨기기"
        }
      },
      "ja": {
        "tabs": {},
        "monitor": {},
        "status": {},
        "severity": {},
        "alertStatus": {},
        "alertActions": {},
        "stats": {},
        "schedulePresets": {},
        "trend": {},
        "empty": {},
        "messages": {},
        "confirm": {},
        "table": {},
        "columnDrilldown": {
          "tabs": {},
          "filter": {},
          "sort": {},
          "levels": {}
        },
        "columnStats": {},
        "preview": {},
        "rootCause": {
          "causes": {},
          "actions": {}
        },
        "sampling": {},
        "largeDataset": {},
        "progress": {}
      },
      "zh": {
        "tabs": {},
        "monitor": {},
        "status": {},
        "severity": {},
        "alertStatus": {},
        "alertActions": {},
        "stats": {},
        "schedulePresets": {},
        "trend": {},
        "empty": {},
        "messages": {},
        "confirm": {},
        "table": {},
        "columnDrilldown": {
          "tabs": {},
          "filter": {},
          "sort": {},
          "levels": {}
        },
        "columnStats": {},
        "preview": {},
        "rootCause": {
          "causes": {},
          "actions": {}
        },
        "sampling": {},
        "largeDataset": {},
        "progress": {}
      },
      "de": {
        "tabs": {},
        "monitor": {},
        "status": {},
        "severity": {},
        "alertStatus": {},
        "alertActions": {},
        "stats": {},
        "schedulePresets": {},
        "trend": {},
        "empty": {},
        "messages": {},
        "confirm": {},
        "table": {},
        "columnDrilldown": {
          "tabs": {},
          "filter": {},
          "sort": {},
          "levels": {}
        },
        "columnStats": {},
        "preview": {},
        "rootCause": {
          "causes": {},
          "actions": {}
        },
        "sampling": {},
        "largeDataset": {},
        "progress": {}
      },
      "fr": {
        "tabs": {},
        "monitor": {},
        "status": {},
        "severity": {},
        "alertStatus": {},
        "alertActions": {},
        "stats": {},
        "schedulePresets": {},
        "trend": {},
        "empty": {},
        "messages": {},
        "confirm": {},
        "table": {},
        "columnDrilldown": {
          "tabs": {},
          "filter": {},
          "sort": {},
          "levels": {}
        },
        "columnStats": {},
        "preview": {},
        "rootCause": {
          "causes": {},
          "actions": {}
        },
        "sampling": {},
        "largeDataset": {},
        "progress": {}
      },
      "es": {
        "tabs": {},
        "monitor": {},
        "status": {},
        "severity": {},
        "alertStatus": {},
        "alertActions": {},
        "stats": {},
        "schedulePresets": {},
        "trend": {},
        "empty": {},
        "messages": {},
        "confirm": {},
        "table": {},
        "columnDrilldown": {
          "tabs": {},
          "filter": {},
          "sort": {},
          "levels": {}
        },
        "columnStats": {},
        "preview": {},
        "rootCause": {
          "causes": {},
          "actions": {}
        },
        "sampling": {},
        "largeDataset": {},
        "progress": {}
      },
      "pt": {
        "tabs": {},
        "monitor": {},
        "status": {},
        "severity": {},
        "alertStatus": {},
        "alertActions": {},
        "stats": {},
        "schedulePresets": {},
        "trend": {},
        "empty": {},
        "messages": {},
        "confirm": {},
        "table": {},
        "columnDrilldown": {
          "tabs": {},
          "filter": {},
          "sort": {},
          "levels": {}
        },
        "columnStats": {},
        "preview": {},
        "rootCause": {
          "causes": {},
          "actions": {}
        },
        "sampling": {},
        "largeDataset": {},
        "progress": {}
      },
      "it": {
        "tabs": {},
        "monitor": {},
        "status": {},
        "severity": {},
        "alertStatus": {},
        "alertActions": {},
        "stats": {},
        "schedulePresets": {},
        "trend": {},
        "empty": {},
        "messages": {},
        "confirm": {},
        "table": {},
        "columnDrilldown": {
          "tabs": {},
          "filter": {},
          "sort": {},
          "levels": {}
        },
        "columnStats": {},
        "preview": {},
        "rootCause": {
          "causes": {},
          "actions": {}
        },
        "sampling": {},
        "largeDataset": {},
        "progress": {}
      },
      "ru": {
        "tabs": {},
        "monitor": {},
        "status": {},
        "severity": {},
        "alertStatus": {},
        "alertActions": {},
        "stats": {},
        "schedulePresets": {},
        "trend": {},
        "empty": {},
        "messages": {},
        "confirm": {},
        "table": {},
        "columnDrilldown": {
          "tabs": {},
          "filter": {},
          "sort": {},
          "levels": {}
        },
        "columnStats": {},
        "preview": {},
        "rootCause": {
          "causes": {},
          "actions": {}
        },
        "sampling": {},
        "largeDataset": {},
        "progress": {}
      },
      "ar": {
        "tabs": {},
        "monitor": {},
        "status": {},
        "severity": {},
        "alertStatus": {},
        "alertActions": {},
        "stats": {},
        "schedulePresets": {},
        "trend": {},
        "empty": {},
        "messages": {},
        "confirm": {},
        "table": {},
        "columnDrilldown": {
          "tabs": {},
          "filter": {},
          "sort": {},
          "levels": {}
        },
        "columnStats": {},
        "preview": {},
        "rootCause": {
          "causes": {},
          "actions": {}
        },
        "sampling": {},
        "largeDataset": {},
        "progress": {}
      },
      "th": {
        "tabs": {},
        "monitor": {},
        "status": {},
        "severity": {},
        "alertStatus": {},
        "alertActions": {},
        "stats": {},
        "schedulePresets": {},
        "trend": {},
        "empty": {},
        "messages": {},
        "confirm": {},
        "table": {},
        "columnDrilldown": {
          "tabs": {},
          "filter": {},
          "sort": {},
          "levels": {}
        },
        "columnStats": {},
        "preview": {},
        "rootCause": {
          "causes": {},
          "actions": {}
        },
        "sampling": {},
        "largeDataset": {},
        "progress": {}
      },
      "vi": {
        "tabs": {},
        "monitor": {},
        "status": {},
        "severity": {},
        "alertStatus": {},
        "alertActions": {},
        "stats": {},
        "schedulePresets": {},
        "trend": {},
        "empty": {},
        "messages": {},
        "confirm": {},
        "table": {},
        "columnDrilldown": {
          "tabs": {},
          "filter": {},
          "sort": {},
          "levels": {}
        },
        "columnStats": {},
        "preview": {},
        "rootCause": {
          "causes": {},
          "actions": {}
        },
        "sampling": {},
        "largeDataset": {},
        "progress": {}
      },
      "id": {
        "tabs": {},
        "monitor": {},
        "status": {},
        "severity": {},
        "alertStatus": {},
        "alertActions": {},
        "stats": {},
        "schedulePresets": {},
        "trend": {},
        "empty": {},
        "messages": {},
        "confirm": {},
        "table": {},
        "columnDrilldown": {
          "tabs": {},
          "filter": {},
          "sort": {},
          "levels": {}
        },
        "columnStats": {},
        "preview": {},
        "rootCause": {
          "causes": {},
          "actions": {}
        },
        "sampling": {},
        "largeDataset": {},
        "progress": {}
      },
      "tr": {
        "tabs": {},
        "monitor": {},
        "status": {},
        "severity": {},
        "alertStatus": {},
        "alertActions": {},
        "stats": {},
        "schedulePresets": {},
        "trend": {},
        "empty": {},
        "messages": {},
        "confirm": {},
        "table": {},
        "columnDrilldown": {
          "tabs": {},
          "filter": {},
          "sort": {},
          "levels": {}
        },
        "columnStats": {},
        "preview": {},
        "rootCause": {
          "causes": {},
          "actions": {}
        },
        "sampling": {},
        "largeDataset": {},
        "progress": {}
      }
    }
  },
  "localIds": [
    "driftMonitor::local::src/content/drift-monitor.content.ts"
  ]
} as const;
