/* eslint-disable */
export default {
  "key": "maintenance",
  "content": {
    "nodeType": "translation",
    "translation": {
      "en": {
        "title": "Maintenance",
        "subtitle": "Configure retention policies and manage database maintenance",
        "statusTitle": "Maintenance Status",
        "statusDescription": "Current status of automated maintenance tasks",
        "autoMaintenance": "Auto Maintenance",
        "lastRun": "Last Run",
        "nextRun": "Next Run",
        "runCleanup": "Run Cleanup",
        "runVacuum": "Run VACUUM",
        "retentionTitle": "Retention Policy",
        "retentionDescription": "Configure how long data is retained before automatic cleanup",
        "enableAutoMaintenance": "Enable Auto Maintenance",
        "enableAutoMaintenanceDescription": "Automatically run cleanup tasks daily at 3:00 AM",
        "validationRetentionDays": "Validation Retention (days)",
        "validationRetentionDaysDescription": "Number of days to keep validation results",
        "profileKeepPerSource": "Profiles per Source",
        "profileKeepPerSourceDescription": "Number of profiles to keep per data source",
        "notificationLogRetentionDays": "Notification Log Retention (days)",
        "notificationLogRetentionDaysDescription": "Number of days to keep notification logs",
        "runVacuumOnCleanup": "Run VACUUM on Cleanup",
        "runVacuumOnCleanupDescription": "Reclaim disk space after cleanup",
        "cacheTitle": "Cache Statistics",
        "cacheDescription": "Monitor and manage application cache",
        "totalEntries": "Total Entries",
        "validEntries": "Valid",
        "expiredEntries": "Expired",
        "hitRate": "Hit Rate",
        "clearCache": "Clear Cache",
        "loadFailed": "Failed to load maintenance data",
        "configSaved": "Configuration saved successfully",
        "saveFailed": "Failed to save configuration",
        "cleanupComplete": "Cleanup completed.",
        "recordsDeleted": "records deleted",
        "cleanupFailed": "Failed to run cleanup",
        "vacuumComplete": "VACUUM completed successfully",
        "vacuumFailed": "Failed to run VACUUM",
        "cacheCleared": "Cache cleared successfully",
        "cacheClearFailed": "Failed to clear cache"
      },
      "ko": {
        "title": "유지보수",
        "subtitle": "리텐션 정책 구성 및 데이터베이스 유지보수 관리",
        "statusTitle": "유지보수 상태",
        "statusDescription": "자동 유지보수 작업의 현재 상태",
        "autoMaintenance": "자동 유지보수",
        "lastRun": "마지막 실행",
        "nextRun": "다음 실행",
        "runCleanup": "정리 실행",
        "runVacuum": "VACUUM 실행",
        "retentionTitle": "리텐션 정책",
        "retentionDescription": "자동 정리 전 데이터 보관 기간 설정",
        "enableAutoMaintenance": "자동 유지보수 활성화",
        "enableAutoMaintenanceDescription": "매일 오전 3시에 자동으로 정리 작업 실행",
        "validationRetentionDays": "검증 결과 보관 기간 (일)",
        "validationRetentionDaysDescription": "검증 결과를 보관할 일수",
        "profileKeepPerSource": "소스당 프로파일 수",
        "profileKeepPerSourceDescription": "데이터 소스당 보관할 프로파일 수",
        "notificationLogRetentionDays": "알림 로그 보관 기간 (일)",
        "notificationLogRetentionDaysDescription": "알림 로그를 보관할 일수",
        "runVacuumOnCleanup": "정리 시 VACUUM 실행",
        "runVacuumOnCleanupDescription": "정리 후 디스크 공간 회수",
        "cacheTitle": "캐시 통계",
        "cacheDescription": "애플리케이션 캐시 모니터링 및 관리",
        "totalEntries": "총 항목",
        "validEntries": "유효",
        "expiredEntries": "만료됨",
        "hitRate": "적중률",
        "clearCache": "캐시 삭제",
        "loadFailed": "유지보수 데이터 로드 실패",
        "configSaved": "설정이 저장되었습니다",
        "saveFailed": "설정 저장 실패",
        "cleanupComplete": "정리 완료.",
        "recordsDeleted": "개 레코드 삭제됨",
        "cleanupFailed": "정리 실행 실패",
        "vacuumComplete": "VACUUM이 성공적으로 완료됨",
        "vacuumFailed": "VACUUM 실행 실패",
        "cacheCleared": "캐시가 삭제되었습니다",
        "cacheClearFailed": "캐시 삭제 실패"
      },
      "ja": {},
      "zh": {},
      "de": {},
      "fr": {},
      "es": {},
      "pt": {},
      "it": {},
      "ru": {},
      "ar": {},
      "th": {},
      "vi": {},
      "id": {},
      "tr": {}
    }
  },
  "localIds": [
    "maintenance::local::src/content/maintenance.content.ts"
  ]
} as const;
