/* eslint-disable */
export default {
  "key": "nav",
  "content": {
    "nodeType": "translation",
    "translation": {
      "en": {
        "dashboard": "Dashboard",
        "sources": "Data Sources",
        "catalog": "Catalog",
        "glossary": "Glossary",
        "rules": "Rules",
        "validations": "Validations",
        "history": "History",
        "schedules": "Schedules",
        "activity": "Activity",
        "notifications": "Notifications",
        "profile": "Profile",
        "drift": "Drift",
        "driftMonitoring": "Drift Monitoring",
        "lineage": "Lineage",
        "anomaly": "Anomaly Detection",
        "privacy": "Privacy",
        "modelMonitoring": "Model Monitoring",
        "notificationsAdvanced": "Advanced Notifications",
        "alerts": "Alerts",
        "settings": "Settings",
        "maintenance": "Maintenance",
        "reports": "Reports",
        "plugins": "Plugins",
        "sections": {
          "dataManagement": "Data Management",
          "dataQuality": "Data Quality",
          "mlMonitoring": "ML & Monitoring",
          "system": "System"
        }
      },
      "ko": {
        "dashboard": "대시보드",
        "sources": "데이터 소스",
        "catalog": "카탈로그",
        "glossary": "용어집",
        "rules": "규칙",
        "validations": "검증",
        "history": "히스토리",
        "schedules": "스케줄",
        "activity": "활동",
        "notifications": "알림",
        "profile": "프로필",
        "drift": "드리프트",
        "driftMonitoring": "드리프트 모니터링",
        "lineage": "리니지",
        "anomaly": "이상 탐지",
        "privacy": "프라이버시",
        "modelMonitoring": "모델 모니터링",
        "notificationsAdvanced": "고급 알림",
        "alerts": "알림 센터",
        "settings": "설정",
        "maintenance": "유지보수",
        "reports": "리포트",
        "plugins": "플러그인",
        "sections": {
          "dataManagement": "데이터 관리",
          "dataQuality": "데이터 품질",
          "mlMonitoring": "ML & 모니터링",
          "system": "시스템"
        }
      },
      "ja": {
        "dashboard": "ダッシュボード",
        "sources": "データソース",
        "catalog": "カタログ",
        "glossary": "用語集",
        "rules": "ルール",
        "validations": "検証",
        "history": "履歴",
        "schedules": "スケジュール",
        "activity": "アクティビティ",
        "notifications": "通知",
        "profile": "プロフィール",
        "drift": "ドリフト",
        "driftMonitoring": "ドリフトモニタリング",
        "lineage": "リネージ",
        "anomaly": "異常検出",
        "privacy": "プライバシー",
        "modelMonitoring": "モデルモニタリング",
        "notificationsAdvanced": "高度な通知",
        "alerts": "アラート",
        "settings": "設定",
        "maintenance": "メンテナンス",
        "reports": "レポート",
        "plugins": "プラグイン",
        "sections": {
          "dataManagement": "データ管理",
          "dataQuality": "データ品質",
          "mlMonitoring": "MLとモニタリング",
          "system": "システム"
        }
      },
      "zh": {
        "dashboard": "仪表板",
        "sources": "数据源",
        "catalog": "目录",
        "glossary": "术语表",
        "rules": "规则",
        "validations": "验证",
        "history": "历史",
        "schedules": "计划",
        "activity": "活动",
        "notifications": "通知",
        "profile": "配置文件",
        "drift": "漂移",
        "driftMonitoring": "漂移监控",
        "lineage": "血统",
        "anomaly": "异常检测",
        "privacy": "隐私",
        "modelMonitoring": "模型监控",
        "notificationsAdvanced": "高级通知",
        "alerts": "警报",
        "settings": "设置",
        "maintenance": "维护",
        "reports": "报告",
        "plugins": "插件",
        "sections": {
          "dataManagement": "数据管理",
          "dataQuality": "数据质量",
          "mlMonitoring": "ML与监控",
          "system": "系统"
        }
      },
      "de": {
        "dashboard": "Dashboard",
        "sources": "Datenquellen",
        "catalog": "Katalog",
        "glossary": "Glossar",
        "rules": "Regeln",
        "validations": "Validierungen",
        "history": "Verlauf",
        "schedules": "Zeitpläne",
        "activity": "Aktivität",
        "notifications": "Benachrichtigungen",
        "profile": "Profil",
        "drift": "Drift",
        "driftMonitoring": "Drift-Überwachung",
        "lineage": "Abstammung",
        "anomaly": "Anomalieerkennung",
        "privacy": "Datenschutz",
        "modelMonitoring": "Modellüberwachung",
        "notificationsAdvanced": "Erweiterte Benachrichtigungen",
        "alerts": "Warnungen",
        "settings": "Einstellungen",
        "maintenance": "Wartung",
        "reports": "Berichte",
        "plugins": "Plugins",
        "sections": {
          "dataManagement": "Datenverwaltung",
          "dataQuality": "Datenqualität",
          "mlMonitoring": "ML & Überwachung",
          "system": "System"
        }
      },
      "fr": {
        "dashboard": "Tableau de bord",
        "sources": "Sources de données",
        "catalog": "Catalogue",
        "glossary": "Glossaire",
        "rules": "Règles",
        "validations": "Validations",
        "history": "Historique",
        "schedules": "Planifications",
        "activity": "Activité",
        "notifications": "Notifications",
        "profile": "Profil",
        "drift": "Dérive",
        "driftMonitoring": "Surveillance de dérive",
        "lineage": "Lignage",
        "anomaly": "Détection d'anomalies",
        "privacy": "Confidentialité",
        "modelMonitoring": "Surveillance de modèle",
        "notificationsAdvanced": "Notifications avancées",
        "alerts": "Alertes",
        "settings": "Paramètres",
        "maintenance": "Maintenance",
        "reports": "Rapports",
        "plugins": "Plugins",
        "sections": {
          "dataManagement": "Gestion des données",
          "dataQuality": "Qualité des données",
          "mlMonitoring": "ML et surveillance",
          "system": "Système"
        }
      },
      "es": {
        "dashboard": "Panel",
        "sources": "Fuentes de datos",
        "catalog": "Catálogo",
        "glossary": "Glosario",
        "rules": "Reglas",
        "validations": "Validaciones",
        "history": "Historial",
        "schedules": "Programaciones",
        "activity": "Actividad",
        "notifications": "Notificaciones",
        "profile": "Perfil",
        "drift": "Deriva",
        "driftMonitoring": "Monitoreo de deriva",
        "lineage": "Linaje",
        "anomaly": "Detección de anomalías",
        "privacy": "Privacidad",
        "modelMonitoring": "Monitoreo de modelo",
        "notificationsAdvanced": "Notificaciones avanzadas",
        "alerts": "Alertas",
        "settings": "Configuración",
        "maintenance": "Mantenimiento",
        "reports": "Informes",
        "plugins": "Plugins",
        "sections": {
          "dataManagement": "Gestión de datos",
          "dataQuality": "Calidad de datos",
          "mlMonitoring": "ML y monitoreo",
          "system": "Sistema"
        }
      },
      "pt": {
        "dashboard": "Painel",
        "sources": "Fontes de dados",
        "catalog": "Catálogo",
        "glossary": "Glossário",
        "rules": "Regras",
        "validations": "Validações",
        "history": "Histórico",
        "schedules": "Agendamentos",
        "activity": "Atividade",
        "notifications": "Notificações",
        "profile": "Perfil",
        "drift": "Drift",
        "driftMonitoring": "Monitoramento de drift",
        "lineage": "Linhagem",
        "anomaly": "Detecção de anomalias",
        "privacy": "Privacidade",
        "modelMonitoring": "Monitoramento de modelo",
        "notificationsAdvanced": "Notificações avançadas",
        "alerts": "Alertas",
        "settings": "Configurações",
        "maintenance": "Manutenção",
        "reports": "Relatórios",
        "plugins": "Plugins",
        "sections": {
          "dataManagement": "Gestão de dados",
          "dataQuality": "Qualidade de dados",
          "mlMonitoring": "ML e monitoramento",
          "system": "Sistema"
        }
      },
      "it": {
        "dashboard": "Dashboard",
        "sources": "Origini dati",
        "catalog": "Catalogo",
        "glossary": "Glossario",
        "rules": "Regole",
        "validations": "Validazioni",
        "history": "Cronologia",
        "schedules": "Pianificazioni",
        "activity": "Attività",
        "notifications": "Notifiche",
        "profile": "Profilo",
        "drift": "Deriva",
        "driftMonitoring": "Monitoraggio deriva",
        "lineage": "Lineage",
        "anomaly": "Rilevamento anomalie",
        "privacy": "Privacy",
        "modelMonitoring": "Monitoraggio modello",
        "notificationsAdvanced": "Notifiche avanzate",
        "alerts": "Avvisi",
        "settings": "Impostazioni",
        "maintenance": "Manutenzione",
        "reports": "Report",
        "plugins": "Plugin",
        "sections": {
          "dataManagement": "Gestione dati",
          "dataQuality": "Qualità dei dati",
          "mlMonitoring": "ML e monitoraggio",
          "system": "Sistema"
        }
      },
      "ru": {
        "dashboard": "Панель",
        "sources": "Источники данных",
        "catalog": "Каталог",
        "glossary": "Глоссарий",
        "rules": "Правила",
        "validations": "Валидации",
        "history": "История",
        "schedules": "Расписания",
        "activity": "Активность",
        "notifications": "Уведомления",
        "profile": "Профиль",
        "drift": "Дрейф",
        "driftMonitoring": "Мониторинг дрейфа",
        "lineage": "Происхождение",
        "anomaly": "Обнаружение аномалий",
        "privacy": "Конфиденциальность",
        "modelMonitoring": "Мониторинг модели",
        "notificationsAdvanced": "Расширенные уведомления",
        "alerts": "Оповещения",
        "settings": "Настройки",
        "maintenance": "Обслуживание",
        "reports": "Отчёты",
        "plugins": "Плагины",
        "sections": {
          "dataManagement": "Управление данными",
          "dataQuality": "Качество данных",
          "mlMonitoring": "ML и мониторинг",
          "system": "Система"
        }
      },
      "ar": {
        "dashboard": "لوحة التحكم",
        "sources": "مصادر البيانات",
        "catalog": "الكتالوج",
        "glossary": "قاموس المصطلحات",
        "rules": "القواعد",
        "validations": "التحققات",
        "history": "السجل",
        "schedules": "الجداول",
        "activity": "النشاط",
        "notifications": "الإشعارات",
        "profile": "الملف الشخصي",
        "drift": "الانحراف",
        "driftMonitoring": "مراقبة الانحراف",
        "lineage": "النسب",
        "anomaly": "اكتشاف الشذوذ",
        "privacy": "الخصوصية",
        "modelMonitoring": "مراقبة النموذج",
        "notificationsAdvanced": "إشعارات متقدمة",
        "alerts": "التنبيهات",
        "settings": "الإعدادات",
        "maintenance": "الصيانة",
        "reports": "التقارير",
        "plugins": "الإضافات",
        "sections": {
          "dataManagement": "إدارة البيانات",
          "dataQuality": "جودة البيانات",
          "mlMonitoring": "ML والمراقبة",
          "system": "النظام"
        }
      },
      "th": {
        "dashboard": "แดชบอร์ด",
        "sources": "แหล่งข้อมูล",
        "catalog": "แคตาล็อก",
        "glossary": "อภิธานศัพท์",
        "rules": "กฎ",
        "validations": "การตรวจสอบ",
        "history": "ประวัติ",
        "schedules": "ตารางเวลา",
        "activity": "กิจกรรม",
        "notifications": "การแจ้งเตือน",
        "profile": "โปรไฟล์",
        "drift": "Drift",
        "driftMonitoring": "การตรวจสอบ Drift",
        "lineage": "Lineage",
        "anomaly": "การตรวจจับความผิดปกติ",
        "privacy": "ความเป็นส่วนตัว",
        "modelMonitoring": "การตรวจสอบโมเดล",
        "notificationsAdvanced": "การแจ้งเตือนขั้นสูง",
        "alerts": "การแจ้งเตือน",
        "settings": "การตั้งค่า",
        "maintenance": "การบำรุงรักษา",
        "reports": "รายงาน",
        "plugins": "ปลั๊กอิน",
        "sections": {
          "dataManagement": "การจัดการข้อมูล",
          "dataQuality": "คุณภาพข้อมูล",
          "mlMonitoring": "ML และการตรวจสอบ",
          "system": "ระบบ"
        }
      },
      "vi": {
        "dashboard": "Bảng điều khiển",
        "sources": "Nguồn dữ liệu",
        "catalog": "Danh mục",
        "glossary": "Từ điển thuật ngữ",
        "rules": "Quy tắc",
        "validations": "Xác thực",
        "history": "Lịch sử",
        "schedules": "Lịch trình",
        "activity": "Hoạt động",
        "notifications": "Thông báo",
        "profile": "Hồ sơ",
        "drift": "Trôi dạt",
        "driftMonitoring": "Giám sát trôi dạt",
        "lineage": "Dòng dõi",
        "anomaly": "Phát hiện bất thường",
        "privacy": "Quyền riêng tư",
        "modelMonitoring": "Giám sát mô hình",
        "notificationsAdvanced": "Thông báo nâng cao",
        "alerts": "Cảnh báo",
        "settings": "Cài đặt",
        "maintenance": "Bảo trì",
        "reports": "Báo cáo",
        "plugins": "Plugin",
        "sections": {
          "dataManagement": "Quản lý dữ liệu",
          "dataQuality": "Chất lượng dữ liệu",
          "mlMonitoring": "ML & Giám sát",
          "system": "Hệ thống"
        }
      },
      "id": {
        "dashboard": "Dasbor",
        "sources": "Sumber Data",
        "catalog": "Katalog",
        "glossary": "Glosarium",
        "rules": "Aturan",
        "validations": "Validasi",
        "history": "Riwayat",
        "schedules": "Jadwal",
        "activity": "Aktivitas",
        "notifications": "Notifikasi",
        "profile": "Profil",
        "drift": "Drift",
        "driftMonitoring": "Pemantauan Drift",
        "lineage": "Garis Keturunan",
        "anomaly": "Deteksi Anomali",
        "privacy": "Privasi",
        "modelMonitoring": "Pemantauan Model",
        "notificationsAdvanced": "Notifikasi Lanjutan",
        "alerts": "Peringatan",
        "settings": "Pengaturan",
        "maintenance": "Pemeliharaan",
        "reports": "Laporan",
        "plugins": "Plugin",
        "sections": {
          "dataManagement": "Manajemen Data",
          "dataQuality": "Kualitas Data",
          "mlMonitoring": "ML & Pemantauan",
          "system": "Sistem"
        }
      },
      "tr": {
        "dashboard": "Gösterge Paneli",
        "sources": "Veri Kaynakları",
        "catalog": "Katalog",
        "glossary": "Sözlük",
        "rules": "Kurallar",
        "validations": "Doğrulamalar",
        "history": "Geçmiş",
        "schedules": "Zamanlamalar",
        "activity": "Etkinlik",
        "notifications": "Bildirimler",
        "profile": "Profil",
        "drift": "Sapma",
        "driftMonitoring": "Sapma İzleme",
        "lineage": "Soy Ağacı",
        "anomaly": "Anomali Tespiti",
        "privacy": "Gizlilik",
        "modelMonitoring": "Model İzleme",
        "notificationsAdvanced": "Gelişmiş Bildirimler",
        "alerts": "Uyarılar",
        "settings": "Ayarlar",
        "maintenance": "Bakım",
        "reports": "Raporlar",
        "plugins": "Eklentiler",
        "sections": {
          "dataManagement": "Veri Yönetimi",
          "dataQuality": "Veri Kalitesi",
          "mlMonitoring": "ML ve İzleme",
          "system": "Sistem"
        }
      }
    }
  },
  "localIds": [
    "nav::local::src/content/nav.content.ts"
  ]
} as const;
