/* eslint-disable */
export default {
  "key": "profileComparison",
  "content": {
    "nodeType": "translation",
    "translation": {
      "en": {
        "comparisonSummary": "Comparison Summary",
        "columnDetails": "Column Details",
        "profileHistory": "Profile History",
        "profileTrends": "Profile Trends",
        "comparingProfiles": "Comparing profiles from",
        "to": "to",
        "totalColumns": "Total Columns",
        "withChanges": "With Changes",
        "significantChanges": "Significant",
        "improved": "Improved",
        "degraded": "Degraded",
        "rowCountChange": "Row Count Change",
        "column": "Column",
        "metric": "Metric",
        "baseline": "Baseline",
        "current": "Current",
        "change": "Change",
        "trend": "Trend",
        "profilesAvailable": "profiles available",
        "selectProfiles": "Select 2 profiles to compare",
        "selectOneMore": "Select 1 more profile",
        "readyToCompare": "Ready to compare",
        "compareSelected": "Compare Selected",
        "comparing": "Comparing...",
        "baselineLabel": "Baseline",
        "currentLabel": "Current",
        "latest": "Latest",
        "date": "Date",
        "rows": "Rows",
        "columns": "Columns",
        "size": "Size",
        "nullPct": "Null %",
        "uniquePct": "Unique %",
        "granularity": "Granularity",
        "daily": "Daily",
        "weekly": "Weekly",
        "monthly": "Monthly",
        "rowCountOverTime": "Row Count Over Time",
        "dataQualityMetrics": "Data Quality Metrics",
        "avgNullAndUnique": "Average null and unique percentages over time",
        "rowCount": "Row Count",
        "avgNullPct": "Avg Null %",
        "avgUniquePct": "Avg Unique %",
        "up": "up",
        "down": "down",
        "stable": "stable",
        "dataPoints": "data points",
        "noProfileHistory": "No profile history available.",
        "runProfilingFirst": "Run profiling to create the first snapshot.",
        "loadingHistory": "Loading profile history...",
        "notEnoughProfiles": "Not enough profiles to compare. Need at least 2 profiles.",
        "periodFrom": "from",
        "periodTo": "to"
      },
      "ko": {
        "comparisonSummary": "비교 요약",
        "columnDetails": "컬럼 상세",
        "profileHistory": "프로파일 이력",
        "profileTrends": "프로파일 추이",
        "comparingProfiles": "프로파일 비교:",
        "to": "에서",
        "totalColumns": "전체 컬럼",
        "withChanges": "변경됨",
        "significantChanges": "중요 변경",
        "improved": "개선됨",
        "degraded": "악화됨",
        "rowCountChange": "행 수 변화",
        "column": "컬럼",
        "metric": "지표",
        "baseline": "기준",
        "current": "현재",
        "change": "변화",
        "trend": "추이",
        "profilesAvailable": "개의 프로파일 사용 가능",
        "selectProfiles": "비교할 2개의 프로파일을 선택하세요",
        "selectOneMore": "1개의 프로파일을 더 선택하세요",
        "readyToCompare": "비교 준비 완료",
        "compareSelected": "선택 항목 비교",
        "comparing": "비교 중...",
        "baselineLabel": "기준",
        "currentLabel": "현재",
        "latest": "최신",
        "date": "날짜",
        "rows": "행",
        "columns": "컬럼",
        "size": "크기",
        "nullPct": "Null %",
        "uniquePct": "고유 %",
        "granularity": "단위",
        "daily": "일별",
        "weekly": "주별",
        "monthly": "월별",
        "rowCountOverTime": "시간별 행 수",
        "dataQualityMetrics": "데이터 품질 지표",
        "avgNullAndUnique": "시간별 평균 null 및 고유 비율",
        "rowCount": "행 수",
        "avgNullPct": "평균 Null %",
        "avgUniquePct": "평균 고유 %",
        "up": "증가",
        "down": "감소",
        "stable": "안정",
        "dataPoints": "개의 데이터 포인트",
        "noProfileHistory": "프로파일 이력이 없습니다.",
        "runProfilingFirst": "프로파일링을 실행하여 첫 스냅샷을 생성하세요.",
        "loadingHistory": "프로파일 이력 로딩 중...",
        "notEnoughProfiles": "비교할 프로파일이 부족합니다. 최소 2개의 프로파일이 필요합니다.",
        "periodFrom": "시작",
        "periodTo": "종료"
      }
    }
  },
  "localIds": [
    "profileComparison::local::src/content/profile-comparison.content.ts"
  ]
} as const;
