/* eslint-disable */
export default {
  "key": "reports",
  "content": {
    "nodeType": "translation",
    "translation": {
      "en": {
        "pageTitle": "Reports",
        "pageDescription": "View and manage generated validation reports",
        "downloadReport": "Download Report",
        "selectFormat": "Select Format",
        "selectTheme": "Select Theme",
        "selectLanguage": "Report Language",
        "formatHtml": "HTML",
        "formatCsv": "CSV",
        "formatJson": "JSON",
        "formatMarkdown": "Markdown",
        "formatPdf": "PDF",
        "formatJunit": "JUnit XML (CI/CD)",
        "formatExcel": "Excel",
        "themeLight": "Light",
        "themeDark": "Dark",
        "themeProfessional": "Professional",
        "themeMinimal": "Minimal",
        "themeHighContrast": "High Contrast",
        "languageEnglish": "English",
        "languageKorean": "Korean",
        "languageJapanese": "Japanese",
        "languageChinese": "Chinese",
        "languageGerman": "German",
        "languageFrench": "French",
        "languageSpanish": "Spanish",
        "languagePortuguese": "Portuguese",
        "languageItalian": "Italian",
        "languageRussian": "Russian",
        "languageArabic": "Arabic",
        "languageThai": "Thai",
        "languageVietnamese": "Vietnamese",
        "languageIndonesian": "Indonesian",
        "languageTurkish": "Turkish",
        "downloadSuccess": "Download Started",
        "reportDownloaded": "report downloaded",
        "downloadFailed": "Failed to download report",
        "previewReport": "Preview Report",
        "customReporters": "Custom Reporters",
        "noConfigRequired": "No configuration required.",
        "generateReport": "Generate Report",
        "generating": "Generating...",
        "customReportDownloaded": "Custom report downloaded",
        "configureReporter": "Configure and generate custom report",
        "clickToGenerate": "Click generate to create the report",
        "languageSelectionHint": "Select the language for report content (15 languages supported)",
        "defaultLanguage": "Default (English)",
        "reportHistory": "Report History",
        "historyDescription": "Browse and download previously generated reports",
        "noReports": "No reports found",
        "noReportsDescription": "Generate a report from a validation result to see it here",
        "statistics": "Statistics",
        "totalReports": "Total Reports",
        "totalSize": "Total Size",
        "totalDownloads": "Total Downloads",
        "avgGenerationTime": "Avg. Generation Time",
        "expiredReports": "Expired Reports",
        "reportersUsed": "Reporters Used",
        "statusPending": "Pending",
        "statusGenerating": "Generating",
        "statusCompleted": "Completed",
        "statusFailed": "Failed",
        "statusExpired": "Expired",
        "filterByFormat": "Filter by Format",
        "filterByStatus": "Filter by Status",
        "filterBySource": "Filter by Source",
        "includeExpired": "Include Expired",
        "searchPlaceholder": "Search reports...",
        "allFormats": "All Formats",
        "allStatuses": "All Statuses",
        "allSources": "All Sources",
        "download": "Download",
        "delete": "Delete",
        "regenerate": "Regenerate",
        "viewDetails": "View Details",
        "bulkGenerate": "Bulk Generate",
        "cleanupExpired": "Cleanup Expired",
        "manageReporters": "Manage Reporters",
        "reportName": "Report Name",
        "format": "Format",
        "status": "Status",
        "source": "Source",
        "validation": "Validation",
        "reporter": "Reporter",
        "theme": "Theme",
        "locale": "Language",
        "fileSize": "File Size",
        "generationTime": "Generation Time",
        "downloadCount": "Download Count",
        "createdAt": "Created At",
        "expiresAt": "Expires At",
        "errorMessage": "Error Message",
        "neverExpires": "Never Expires",
        "noSource": "No Source",
        "noReporter": "Standard Reporter",
        "bulkGenerateTitle": "Bulk Generate Reports",
        "bulkGenerateDescription": "Generate reports for multiple validations at once",
        "selectValidations": "Select Validations",
        "selectedCount": "selected",
        "generateSelected": "Generate Selected",
        "bulkSuccess": "Bulk generation completed",
        "bulkPartialSuccess": "Bulk generation partially completed",
        "cleanupTitle": "Cleanup Expired Reports",
        "cleanupDescription": "Delete all expired reports to free up storage",
        "cleanupConfirm": "Are you sure you want to delete all expired reports?",
        "cleanupSuccess": "reports deleted",
        "deleteConfirmTitle": "Delete Report",
        "deleteConfirmMessage": "Are you sure you want to delete this report? This action cannot be undone.",
        "deleteSuccess": "Report deleted successfully"
      },
      "ko": {
        "pageTitle": "리포트",
        "pageDescription": "생성된 검증 리포트 조회 및 관리",
        "downloadReport": "리포트 다운로드",
        "selectFormat": "형식 선택",
        "selectTheme": "테마 선택",
        "selectLanguage": "리포트 언어",
        "formatHtml": "HTML",
        "formatCsv": "CSV",
        "formatJson": "JSON",
        "formatMarkdown": "Markdown",
        "formatPdf": "PDF",
        "formatJunit": "JUnit XML (CI/CD)",
        "formatExcel": "Excel",
        "themeLight": "라이트",
        "themeDark": "다크",
        "themeProfessional": "프로페셔널",
        "themeMinimal": "미니멀",
        "themeHighContrast": "고대비",
        "languageEnglish": "영어",
        "languageKorean": "한국어",
        "languageJapanese": "일본어",
        "languageChinese": "중국어",
        "languageGerman": "독일어",
        "languageFrench": "프랑스어",
        "languageSpanish": "스페인어",
        "languagePortuguese": "포르투갈어",
        "languageItalian": "이탈리아어",
        "languageRussian": "러시아어",
        "languageArabic": "아랍어",
        "languageThai": "태국어",
        "languageVietnamese": "베트남어",
        "languageIndonesian": "인도네시아어",
        "languageTurkish": "터키어",
        "downloadSuccess": "다운로드 시작됨",
        "reportDownloaded": "리포트 다운로드됨",
        "downloadFailed": "리포트 다운로드 실패",
        "previewReport": "리포트 미리보기",
        "customReporters": "커스텀 리포터",
        "noConfigRequired": "설정이 필요하지 않습니다.",
        "generateReport": "리포트 생성",
        "generating": "생성 중...",
        "customReportDownloaded": "커스텀 리포트 다운로드됨",
        "configureReporter": "커스텀 리포트 설정 및 생성",
        "clickToGenerate": "생성 버튼을 클릭하여 리포트 생성",
        "languageSelectionHint": "리포트 콘텐츠 언어 선택 (15개 언어 지원)",
        "defaultLanguage": "기본값 (영어)",
        "reportHistory": "리포트 이력",
        "historyDescription": "이전에 생성된 리포트 조회 및 다운로드",
        "noReports": "리포트가 없습니다",
        "noReportsDescription": "검증 결과에서 리포트를 생성하면 여기에 표시됩니다",
        "statistics": "통계",
        "totalReports": "총 리포트",
        "totalSize": "총 용량",
        "totalDownloads": "총 다운로드",
        "avgGenerationTime": "평균 생성 시간",
        "expiredReports": "만료된 리포트",
        "reportersUsed": "사용된 리포터",
        "statusPending": "대기 중",
        "statusGenerating": "생성 중",
        "statusCompleted": "완료",
        "statusFailed": "실패",
        "statusExpired": "만료",
        "filterByFormat": "형식별 필터",
        "filterByStatus": "상태별 필터",
        "filterBySource": "소스별 필터",
        "includeExpired": "만료된 항목 포함",
        "searchPlaceholder": "리포트 검색...",
        "allFormats": "모든 형식",
        "allStatuses": "모든 상태",
        "allSources": "모든 소스",
        "download": "다운로드",
        "delete": "삭제",
        "regenerate": "재생성",
        "viewDetails": "상세 보기",
        "bulkGenerate": "일괄 생성",
        "cleanupExpired": "만료 정리",
        "manageReporters": "리포터 관리",
        "reportName": "리포트 이름",
        "format": "형식",
        "status": "상태",
        "source": "소스",
        "validation": "검증",
        "reporter": "리포터",
        "theme": "테마",
        "locale": "언어",
        "fileSize": "파일 크기",
        "generationTime": "생성 시간",
        "downloadCount": "다운로드 횟수",
        "createdAt": "생성일",
        "expiresAt": "만료일",
        "errorMessage": "오류 메시지",
        "neverExpires": "만료 없음",
        "noSource": "소스 없음",
        "noReporter": "기본 리포터",
        "bulkGenerateTitle": "리포트 일괄 생성",
        "bulkGenerateDescription": "여러 검증에 대한 리포트를 한 번에 생성",
        "selectValidations": "검증 선택",
        "selectedCount": "개 선택됨",
        "generateSelected": "선택 항목 생성",
        "bulkSuccess": "일괄 생성 완료",
        "bulkPartialSuccess": "일괄 생성 부분 완료",
        "cleanupTitle": "만료된 리포트 정리",
        "cleanupDescription": "저장 공간 확보를 위해 만료된 모든 리포트 삭제",
        "cleanupConfirm": "만료된 모든 리포트를 삭제하시겠습니까?",
        "cleanupSuccess": "개 리포트 삭제됨",
        "deleteConfirmTitle": "리포트 삭제",
        "deleteConfirmMessage": "이 리포트를 삭제하시겠습니까? 이 작업은 되돌릴 수 없습니다.",
        "deleteSuccess": "리포트가 삭제되었습니다"
      }
    }
  },
  "localIds": [
    "reports::local::src/content/reports.content.ts"
  ]
} as const;
