"""Message catalogs for report localization.

This module contains pre-defined message catalogs for all supported locales.
Each catalog contains all translatable strings used in report generation.

Message keys follow a hierarchical naming convention:
- report.*: General report elements
- summary.*: Summary section
- statistics.*: Statistics section
- issues.*: Issues section
- severity.*: Severity levels
- status.*: Validation status
- common.*: Common UI elements
"""

from .base import LocaleCatalog, SupportedLocale


# ============================================================================
# English (Base/Fallback)
# ============================================================================
ENGLISH_CATALOG = LocaleCatalog(
    locale=SupportedLocale.ENGLISH,
    messages={
        # Report structure
        "report.title": "Validation Report",
        "report.generated_at": "Generated at",
        "report.source": "Source",
        "report.validation_id": "Validation ID",
        "report.generated_by": "Generated by Truthound Dashboard",

        # Summary section
        "summary.title": "Validation Summary",
        "summary.status": "Status",
        "summary.total_issues": "Total Issues",
        "summary.pass_rate": "Pass Rate",

        # Statistics section
        "statistics.title": "Data Statistics",
        "statistics.row_count": "Row Count",
        "statistics.column_count": "Column Count",
        "statistics.duration": "Duration",
        "statistics.started_at": "Started At",
        "statistics.completed_at": "Completed At",
        "statistics.na": "N/A",

        # Issues section
        "issues.title": "Issues",
        "issues.no_issues": "No issues found. All validations passed.",
        "issues.column": "Column",
        "issues.type": "Issue Type",
        "issues.severity": "Severity",
        "issues.count": "Count",
        "issues.details": "Details",
        "issues.samples": "Sample Values",

        # Severity levels
        "severity.critical": "Critical",
        "severity.high": "High",
        "severity.medium": "Medium",
        "severity.low": "Low",
        "severity.info": "Info",

        # Status indicators
        "status.passed": "Passed",
        "status.failed": "Failed",
        "status.pending": "Pending",
        "status.running": "Running",

        # Plurals (using .one/.other pattern)
        "issues.count.one": "{count} issue",
        "issues.count.other": "{count} issues",
        "rows.count.one": "{count} row",
        "rows.count.other": "{count} rows",

        # Time units
        "time.seconds": "{value}s",
        "time.milliseconds": "{value}ms",

        # Common elements
        "common.yes": "Yes",
        "common.no": "No",
        "common.true": "True",
        "common.false": "False",
    },
)


# ============================================================================
# Korean
# ============================================================================
KOREAN_CATALOG = LocaleCatalog(
    locale=SupportedLocale.KOREAN,
    messages={
        # Report structure
        "report.title": "검증 리포트",
        "report.generated_at": "생성 시간",
        "report.source": "데이터 소스",
        "report.validation_id": "검증 ID",
        "report.generated_by": "Truthound Dashboard에서 생성됨",

        # Summary section
        "summary.title": "검증 요약",
        "summary.status": "상태",
        "summary.total_issues": "총 이슈 수",
        "summary.pass_rate": "통과율",

        # Statistics section
        "statistics.title": "데이터 통계",
        "statistics.row_count": "행 수",
        "statistics.column_count": "열 수",
        "statistics.duration": "소요 시간",
        "statistics.started_at": "시작 시간",
        "statistics.completed_at": "완료 시간",
        "statistics.na": "해당 없음",

        # Issues section
        "issues.title": "이슈 목록",
        "issues.no_issues": "이슈가 없습니다. 모든 검증을 통과했습니다.",
        "issues.column": "컬럼",
        "issues.type": "이슈 유형",
        "issues.severity": "심각도",
        "issues.count": "개수",
        "issues.details": "상세 내용",
        "issues.samples": "샘플 값",

        # Severity levels
        "severity.critical": "심각",
        "severity.high": "높음",
        "severity.medium": "보통",
        "severity.low": "낮음",
        "severity.info": "정보",

        # Status indicators
        "status.passed": "통과",
        "status.failed": "실패",
        "status.pending": "대기 중",
        "status.running": "실행 중",

        # Plurals
        "issues.count.one": "{count}개 이슈",
        "issues.count.other": "{count}개 이슈",
        "rows.count.one": "{count}개 행",
        "rows.count.other": "{count}개 행",

        # Time units
        "time.seconds": "{value}초",
        "time.milliseconds": "{value}밀리초",

        # Common elements
        "common.yes": "예",
        "common.no": "아니오",
        "common.true": "참",
        "common.false": "거짓",
    },
)


# ============================================================================
# Japanese
# ============================================================================
JAPANESE_CATALOG = LocaleCatalog(
    locale=SupportedLocale.JAPANESE,
    messages={
        # Report structure
        "report.title": "検証レポート",
        "report.generated_at": "生成日時",
        "report.source": "データソース",
        "report.validation_id": "検証ID",
        "report.generated_by": "Truthound Dashboardで生成",

        # Summary section
        "summary.title": "検証サマリー",
        "summary.status": "ステータス",
        "summary.total_issues": "総イシュー数",
        "summary.pass_rate": "合格率",

        # Statistics section
        "statistics.title": "データ統計",
        "statistics.row_count": "行数",
        "statistics.column_count": "列数",
        "statistics.duration": "所要時間",
        "statistics.started_at": "開始時刻",
        "statistics.completed_at": "完了時刻",
        "statistics.na": "該当なし",

        # Issues section
        "issues.title": "イシュー一覧",
        "issues.no_issues": "イシューはありません。すべての検証に合格しました。",
        "issues.column": "カラム",
        "issues.type": "イシュータイプ",
        "issues.severity": "重要度",
        "issues.count": "件数",
        "issues.details": "詳細",
        "issues.samples": "サンプル値",

        # Severity levels
        "severity.critical": "致命的",
        "severity.high": "高",
        "severity.medium": "中",
        "severity.low": "低",
        "severity.info": "情報",

        # Status indicators
        "status.passed": "合格",
        "status.failed": "不合格",
        "status.pending": "保留中",
        "status.running": "実行中",

        # Plurals
        "issues.count.one": "{count}件のイシュー",
        "issues.count.other": "{count}件のイシュー",
        "rows.count.one": "{count}行",
        "rows.count.other": "{count}行",

        # Time units
        "time.seconds": "{value}秒",
        "time.milliseconds": "{value}ミリ秒",

        # Common elements
        "common.yes": "はい",
        "common.no": "いいえ",
        "common.true": "真",
        "common.false": "偽",
    },
)


# ============================================================================
# Chinese (Simplified)
# ============================================================================
CHINESE_CATALOG = LocaleCatalog(
    locale=SupportedLocale.CHINESE,
    messages={
        # Report structure
        "report.title": "验证报告",
        "report.generated_at": "生成时间",
        "report.source": "数据源",
        "report.validation_id": "验证ID",
        "report.generated_by": "由Truthound Dashboard生成",

        # Summary section
        "summary.title": "验证摘要",
        "summary.status": "状态",
        "summary.total_issues": "问题总数",
        "summary.pass_rate": "通过率",

        # Statistics section
        "statistics.title": "数据统计",
        "statistics.row_count": "行数",
        "statistics.column_count": "列数",
        "statistics.duration": "耗时",
        "statistics.started_at": "开始时间",
        "statistics.completed_at": "完成时间",
        "statistics.na": "不适用",

        # Issues section
        "issues.title": "问题列表",
        "issues.no_issues": "未发现问题。所有验证均已通过。",
        "issues.column": "列",
        "issues.type": "问题类型",
        "issues.severity": "严重程度",
        "issues.count": "数量",
        "issues.details": "详情",
        "issues.samples": "示例值",

        # Severity levels
        "severity.critical": "严重",
        "severity.high": "高",
        "severity.medium": "中",
        "severity.low": "低",
        "severity.info": "信息",

        # Status indicators
        "status.passed": "通过",
        "status.failed": "失败",
        "status.pending": "待处理",
        "status.running": "运行中",

        # Plurals
        "issues.count.one": "{count}个问题",
        "issues.count.other": "{count}个问题",
        "rows.count.one": "{count}行",
        "rows.count.other": "{count}行",

        # Time units
        "time.seconds": "{value}秒",
        "time.milliseconds": "{value}毫秒",

        # Common elements
        "common.yes": "是",
        "common.no": "否",
        "common.true": "真",
        "common.false": "假",
    },
)


# ============================================================================
# German
# ============================================================================
GERMAN_CATALOG = LocaleCatalog(
    locale=SupportedLocale.GERMAN,
    messages={
        # Report structure
        "report.title": "Validierungsbericht",
        "report.generated_at": "Erstellt am",
        "report.source": "Datenquelle",
        "report.validation_id": "Validierungs-ID",
        "report.generated_by": "Erstellt von Truthound Dashboard",

        # Summary section
        "summary.title": "Validierungszusammenfassung",
        "summary.status": "Status",
        "summary.total_issues": "Gesamtanzahl Probleme",
        "summary.pass_rate": "Erfolgsrate",

        # Statistics section
        "statistics.title": "Datenstatistik",
        "statistics.row_count": "Zeilenanzahl",
        "statistics.column_count": "Spaltenanzahl",
        "statistics.duration": "Dauer",
        "statistics.started_at": "Gestartet um",
        "statistics.completed_at": "Abgeschlossen um",
        "statistics.na": "Nicht verfügbar",

        # Issues section
        "issues.title": "Probleme",
        "issues.no_issues": "Keine Probleme gefunden. Alle Validierungen bestanden.",
        "issues.column": "Spalte",
        "issues.type": "Problemtyp",
        "issues.severity": "Schweregrad",
        "issues.count": "Anzahl",
        "issues.details": "Details",
        "issues.samples": "Beispielwerte",

        # Severity levels
        "severity.critical": "Kritisch",
        "severity.high": "Hoch",
        "severity.medium": "Mittel",
        "severity.low": "Niedrig",
        "severity.info": "Info",

        # Status indicators
        "status.passed": "Bestanden",
        "status.failed": "Fehlgeschlagen",
        "status.pending": "Ausstehend",
        "status.running": "Läuft",

        # Plurals
        "issues.count.one": "{count} Problem",
        "issues.count.other": "{count} Probleme",
        "rows.count.one": "{count} Zeile",
        "rows.count.other": "{count} Zeilen",

        # Time units
        "time.seconds": "{value}s",
        "time.milliseconds": "{value}ms",

        # Common elements
        "common.yes": "Ja",
        "common.no": "Nein",
        "common.true": "Wahr",
        "common.false": "Falsch",
    },
)


# ============================================================================
# French
# ============================================================================
FRENCH_CATALOG = LocaleCatalog(
    locale=SupportedLocale.FRENCH,
    messages={
        # Report structure
        "report.title": "Rapport de Validation",
        "report.generated_at": "Généré le",
        "report.source": "Source de données",
        "report.validation_id": "ID de validation",
        "report.generated_by": "Généré par Truthound Dashboard",

        # Summary section
        "summary.title": "Résumé de la Validation",
        "summary.status": "Statut",
        "summary.total_issues": "Total des problèmes",
        "summary.pass_rate": "Taux de réussite",

        # Statistics section
        "statistics.title": "Statistiques des Données",
        "statistics.row_count": "Nombre de lignes",
        "statistics.column_count": "Nombre de colonnes",
        "statistics.duration": "Durée",
        "statistics.started_at": "Commencé à",
        "statistics.completed_at": "Terminé à",
        "statistics.na": "Non disponible",

        # Issues section
        "issues.title": "Problèmes",
        "issues.no_issues": "Aucun problème trouvé. Toutes les validations ont réussi.",
        "issues.column": "Colonne",
        "issues.type": "Type de problème",
        "issues.severity": "Gravité",
        "issues.count": "Nombre",
        "issues.details": "Détails",
        "issues.samples": "Valeurs d'exemple",

        # Severity levels
        "severity.critical": "Critique",
        "severity.high": "Élevé",
        "severity.medium": "Moyen",
        "severity.low": "Faible",
        "severity.info": "Info",

        # Status indicators
        "status.passed": "Réussi",
        "status.failed": "Échoué",
        "status.pending": "En attente",
        "status.running": "En cours",

        # Plurals
        "issues.count.one": "{count} problème",
        "issues.count.other": "{count} problèmes",
        "rows.count.one": "{count} ligne",
        "rows.count.other": "{count} lignes",

        # Time units
        "time.seconds": "{value}s",
        "time.milliseconds": "{value}ms",

        # Common elements
        "common.yes": "Oui",
        "common.no": "Non",
        "common.true": "Vrai",
        "common.false": "Faux",
    },
)


# ============================================================================
# Spanish
# ============================================================================
SPANISH_CATALOG = LocaleCatalog(
    locale=SupportedLocale.SPANISH,
    messages={
        # Report structure
        "report.title": "Informe de Validación",
        "report.generated_at": "Generado el",
        "report.source": "Fuente de datos",
        "report.validation_id": "ID de validación",
        "report.generated_by": "Generado por Truthound Dashboard",

        # Summary section
        "summary.title": "Resumen de Validación",
        "summary.status": "Estado",
        "summary.total_issues": "Total de problemas",
        "summary.pass_rate": "Tasa de aprobación",

        # Statistics section
        "statistics.title": "Estadísticas de Datos",
        "statistics.row_count": "Número de filas",
        "statistics.column_count": "Número de columnas",
        "statistics.duration": "Duración",
        "statistics.started_at": "Iniciado a las",
        "statistics.completed_at": "Completado a las",
        "statistics.na": "No disponible",

        # Issues section
        "issues.title": "Problemas",
        "issues.no_issues": "No se encontraron problemas. Todas las validaciones pasaron.",
        "issues.column": "Columna",
        "issues.type": "Tipo de problema",
        "issues.severity": "Gravedad",
        "issues.count": "Cantidad",
        "issues.details": "Detalles",
        "issues.samples": "Valores de ejemplo",

        # Severity levels
        "severity.critical": "Crítico",
        "severity.high": "Alto",
        "severity.medium": "Medio",
        "severity.low": "Bajo",
        "severity.info": "Info",

        # Status indicators
        "status.passed": "Aprobado",
        "status.failed": "Fallido",
        "status.pending": "Pendiente",
        "status.running": "Ejecutando",

        # Plurals
        "issues.count.one": "{count} problema",
        "issues.count.other": "{count} problemas",
        "rows.count.one": "{count} fila",
        "rows.count.other": "{count} filas",

        # Time units
        "time.seconds": "{value}s",
        "time.milliseconds": "{value}ms",

        # Common elements
        "common.yes": "Sí",
        "common.no": "No",
        "common.true": "Verdadero",
        "common.false": "Falso",
    },
)


# ============================================================================
# Portuguese
# ============================================================================
PORTUGUESE_CATALOG = LocaleCatalog(
    locale=SupportedLocale.PORTUGUESE,
    messages={
        "report.title": "Relatório de Validação",
        "report.generated_at": "Gerado em",
        "report.source": "Fonte de dados",
        "report.validation_id": "ID de validação",
        "report.generated_by": "Gerado pelo Truthound Dashboard",
        "summary.title": "Resumo da Validação",
        "summary.status": "Status",
        "summary.total_issues": "Total de problemas",
        "summary.pass_rate": "Taxa de aprovação",
        "statistics.title": "Estatísticas dos Dados",
        "statistics.row_count": "Número de linhas",
        "statistics.column_count": "Número de colunas",
        "statistics.duration": "Duração",
        "statistics.started_at": "Iniciado em",
        "statistics.completed_at": "Concluído em",
        "statistics.na": "Não disponível",
        "issues.title": "Problemas",
        "issues.no_issues": "Nenhum problema encontrado. Todas as validações passaram.",
        "issues.column": "Coluna",
        "issues.type": "Tipo de problema",
        "issues.severity": "Gravidade",
        "issues.count": "Quantidade",
        "issues.details": "Detalhes",
        "issues.samples": "Valores de exemplo",
        "severity.critical": "Crítico",
        "severity.high": "Alto",
        "severity.medium": "Médio",
        "severity.low": "Baixo",
        "severity.info": "Info",
        "status.passed": "Aprovado",
        "status.failed": "Falhou",
        "status.pending": "Pendente",
        "status.running": "Executando",
        "issues.count.one": "{count} problema",
        "issues.count.other": "{count} problemas",
        "rows.count.one": "{count} linha",
        "rows.count.other": "{count} linhas",
        "time.seconds": "{value}s",
        "time.milliseconds": "{value}ms",
        "common.yes": "Sim",
        "common.no": "Não",
        "common.true": "Verdadeiro",
        "common.false": "Falso",
    },
)


# ============================================================================
# Italian
# ============================================================================
ITALIAN_CATALOG = LocaleCatalog(
    locale=SupportedLocale.ITALIAN,
    messages={
        "report.title": "Report di Validazione",
        "report.generated_at": "Generato il",
        "report.source": "Origine dati",
        "report.validation_id": "ID validazione",
        "report.generated_by": "Generato da Truthound Dashboard",
        "summary.title": "Riepilogo Validazione",
        "summary.status": "Stato",
        "summary.total_issues": "Totale problemi",
        "summary.pass_rate": "Percentuale superamento",
        "statistics.title": "Statistiche Dati",
        "statistics.row_count": "Numero righe",
        "statistics.column_count": "Numero colonne",
        "statistics.duration": "Durata",
        "statistics.started_at": "Iniziato alle",
        "statistics.completed_at": "Completato alle",
        "statistics.na": "Non disponibile",
        "issues.title": "Problemi",
        "issues.no_issues": "Nessun problema trovato. Tutte le validazioni sono passate.",
        "issues.column": "Colonna",
        "issues.type": "Tipo problema",
        "issues.severity": "Gravità",
        "issues.count": "Conteggio",
        "issues.details": "Dettagli",
        "issues.samples": "Valori di esempio",
        "severity.critical": "Critico",
        "severity.high": "Alto",
        "severity.medium": "Medio",
        "severity.low": "Basso",
        "severity.info": "Info",
        "status.passed": "Superato",
        "status.failed": "Fallito",
        "status.pending": "In attesa",
        "status.running": "In esecuzione",
        "issues.count.one": "{count} problema",
        "issues.count.other": "{count} problemi",
        "rows.count.one": "{count} riga",
        "rows.count.other": "{count} righe",
        "time.seconds": "{value}s",
        "time.milliseconds": "{value}ms",
        "common.yes": "Sì",
        "common.no": "No",
        "common.true": "Vero",
        "common.false": "Falso",
    },
)


# ============================================================================
# Russian
# ============================================================================
RUSSIAN_CATALOG = LocaleCatalog(
    locale=SupportedLocale.RUSSIAN,
    messages={
        "report.title": "Отчёт о валидации",
        "report.generated_at": "Сгенерировано",
        "report.source": "Источник данных",
        "report.validation_id": "ID валидации",
        "report.generated_by": "Создано в Truthound Dashboard",
        "summary.title": "Сводка валидации",
        "summary.status": "Статус",
        "summary.total_issues": "Всего проблем",
        "summary.pass_rate": "Процент успеха",
        "statistics.title": "Статистика данных",
        "statistics.row_count": "Количество строк",
        "statistics.column_count": "Количество столбцов",
        "statistics.duration": "Продолжительность",
        "statistics.started_at": "Начато",
        "statistics.completed_at": "Завершено",
        "statistics.na": "Недоступно",
        "issues.title": "Проблемы",
        "issues.no_issues": "Проблем не обнаружено. Все проверки пройдены.",
        "issues.column": "Столбец",
        "issues.type": "Тип проблемы",
        "issues.severity": "Серьёзность",
        "issues.count": "Количество",
        "issues.details": "Детали",
        "issues.samples": "Примеры значений",
        "severity.critical": "Критическая",
        "severity.high": "Высокая",
        "severity.medium": "Средняя",
        "severity.low": "Низкая",
        "severity.info": "Инфо",
        "status.passed": "Пройдено",
        "status.failed": "Ошибка",
        "status.pending": "Ожидание",
        "status.running": "Выполняется",
        "issues.count.one": "{count} проблема",
        "issues.count.other": "{count} проблем",
        "rows.count.one": "{count} строка",
        "rows.count.other": "{count} строк",
        "time.seconds": "{value}с",
        "time.milliseconds": "{value}мс",
        "common.yes": "Да",
        "common.no": "Нет",
        "common.true": "Истина",
        "common.false": "Ложь",
    },
)


# ============================================================================
# Arabic
# ============================================================================
ARABIC_CATALOG = LocaleCatalog(
    locale=SupportedLocale.ARABIC,
    messages={
        "report.title": "تقرير التحقق",
        "report.generated_at": "تم الإنشاء في",
        "report.source": "مصدر البيانات",
        "report.validation_id": "معرف التحقق",
        "report.generated_by": "تم الإنشاء بواسطة Truthound Dashboard",
        "summary.title": "ملخص التحقق",
        "summary.status": "الحالة",
        "summary.total_issues": "إجمالي المشاكل",
        "summary.pass_rate": "معدل النجاح",
        "statistics.title": "إحصائيات البيانات",
        "statistics.row_count": "عدد الصفوف",
        "statistics.column_count": "عدد الأعمدة",
        "statistics.duration": "المدة",
        "statistics.started_at": "بدأ في",
        "statistics.completed_at": "انتهى في",
        "statistics.na": "غير متاح",
        "issues.title": "المشاكل",
        "issues.no_issues": "لم يتم العثور على مشاكل. نجحت جميع عمليات التحقق.",
        "issues.column": "العمود",
        "issues.type": "نوع المشكلة",
        "issues.severity": "الخطورة",
        "issues.count": "العدد",
        "issues.details": "التفاصيل",
        "issues.samples": "قيم نموذجية",
        "severity.critical": "حرج",
        "severity.high": "عالي",
        "severity.medium": "متوسط",
        "severity.low": "منخفض",
        "severity.info": "معلومات",
        "status.passed": "نجح",
        "status.failed": "فشل",
        "status.pending": "قيد الانتظار",
        "status.running": "قيد التشغيل",
        "issues.count.one": "مشكلة واحدة",
        "issues.count.other": "{count} مشاكل",
        "rows.count.one": "صف واحد",
        "rows.count.other": "{count} صفوف",
        "time.seconds": "{value} ثانية",
        "time.milliseconds": "{value} مللي ثانية",
        "common.yes": "نعم",
        "common.no": "لا",
        "common.true": "صحيح",
        "common.false": "خطأ",
    },
)


# ============================================================================
# Thai
# ============================================================================
THAI_CATALOG = LocaleCatalog(
    locale=SupportedLocale.THAI,
    messages={
        "report.title": "รายงานการตรวจสอบ",
        "report.generated_at": "สร้างเมื่อ",
        "report.source": "แหล่งข้อมูล",
        "report.validation_id": "รหัสการตรวจสอบ",
        "report.generated_by": "สร้างโดย Truthound Dashboard",
        "summary.title": "สรุปการตรวจสอบ",
        "summary.status": "สถานะ",
        "summary.total_issues": "ปัญหาทั้งหมด",
        "summary.pass_rate": "อัตราผ่าน",
        "statistics.title": "สถิติข้อมูล",
        "statistics.row_count": "จำนวนแถว",
        "statistics.column_count": "จำนวนคอลัมน์",
        "statistics.duration": "ระยะเวลา",
        "statistics.started_at": "เริ่มเมื่อ",
        "statistics.completed_at": "เสร็จเมื่อ",
        "statistics.na": "ไม่มีข้อมูล",
        "issues.title": "ปัญหา",
        "issues.no_issues": "ไม่พบปัญหา การตรวจสอบทั้งหมดผ่าน",
        "issues.column": "คอลัมน์",
        "issues.type": "ประเภทปัญหา",
        "issues.severity": "ความรุนแรง",
        "issues.count": "จำนวน",
        "issues.details": "รายละเอียด",
        "issues.samples": "ค่าตัวอย่าง",
        "severity.critical": "วิกฤต",
        "severity.high": "สูง",
        "severity.medium": "ปานกลาง",
        "severity.low": "ต่ำ",
        "severity.info": "ข้อมูล",
        "status.passed": "ผ่าน",
        "status.failed": "ไม่ผ่าน",
        "status.pending": "รอดำเนินการ",
        "status.running": "กำลังทำงาน",
        "issues.count.one": "{count} ปัญหา",
        "issues.count.other": "{count} ปัญหา",
        "rows.count.one": "{count} แถว",
        "rows.count.other": "{count} แถว",
        "time.seconds": "{value} วินาที",
        "time.milliseconds": "{value} มิลลิวินาที",
        "common.yes": "ใช่",
        "common.no": "ไม่",
        "common.true": "จริง",
        "common.false": "เท็จ",
    },
)


# ============================================================================
# Vietnamese
# ============================================================================
VIETNAMESE_CATALOG = LocaleCatalog(
    locale=SupportedLocale.VIETNAMESE,
    messages={
        "report.title": "Báo cáo Xác thực",
        "report.generated_at": "Tạo lúc",
        "report.source": "Nguồn dữ liệu",
        "report.validation_id": "ID xác thực",
        "report.generated_by": "Tạo bởi Truthound Dashboard",
        "summary.title": "Tóm tắt Xác thực",
        "summary.status": "Trạng thái",
        "summary.total_issues": "Tổng số vấn đề",
        "summary.pass_rate": "Tỷ lệ đạt",
        "statistics.title": "Thống kê Dữ liệu",
        "statistics.row_count": "Số hàng",
        "statistics.column_count": "Số cột",
        "statistics.duration": "Thời gian",
        "statistics.started_at": "Bắt đầu lúc",
        "statistics.completed_at": "Hoàn thành lúc",
        "statistics.na": "Không có",
        "issues.title": "Vấn đề",
        "issues.no_issues": "Không tìm thấy vấn đề. Tất cả xác thực đều đạt.",
        "issues.column": "Cột",
        "issues.type": "Loại vấn đề",
        "issues.severity": "Mức độ",
        "issues.count": "Số lượng",
        "issues.details": "Chi tiết",
        "issues.samples": "Giá trị mẫu",
        "severity.critical": "Nghiêm trọng",
        "severity.high": "Cao",
        "severity.medium": "Trung bình",
        "severity.low": "Thấp",
        "severity.info": "Thông tin",
        "status.passed": "Đạt",
        "status.failed": "Không đạt",
        "status.pending": "Đang chờ",
        "status.running": "Đang chạy",
        "issues.count.one": "{count} vấn đề",
        "issues.count.other": "{count} vấn đề",
        "rows.count.one": "{count} hàng",
        "rows.count.other": "{count} hàng",
        "time.seconds": "{value} giây",
        "time.milliseconds": "{value} ms",
        "common.yes": "Có",
        "common.no": "Không",
        "common.true": "Đúng",
        "common.false": "Sai",
    },
)


# ============================================================================
# Indonesian
# ============================================================================
INDONESIAN_CATALOG = LocaleCatalog(
    locale=SupportedLocale.INDONESIAN,
    messages={
        "report.title": "Laporan Validasi",
        "report.generated_at": "Dibuat pada",
        "report.source": "Sumber data",
        "report.validation_id": "ID Validasi",
        "report.generated_by": "Dibuat oleh Truthound Dashboard",
        "summary.title": "Ringkasan Validasi",
        "summary.status": "Status",
        "summary.total_issues": "Total Masalah",
        "summary.pass_rate": "Tingkat Kelulusan",
        "statistics.title": "Statistik Data",
        "statistics.row_count": "Jumlah Baris",
        "statistics.column_count": "Jumlah Kolom",
        "statistics.duration": "Durasi",
        "statistics.started_at": "Dimulai pada",
        "statistics.completed_at": "Selesai pada",
        "statistics.na": "Tidak tersedia",
        "issues.title": "Masalah",
        "issues.no_issues": "Tidak ada masalah ditemukan. Semua validasi berhasil.",
        "issues.column": "Kolom",
        "issues.type": "Jenis Masalah",
        "issues.severity": "Tingkat Keparahan",
        "issues.count": "Jumlah",
        "issues.details": "Detail",
        "issues.samples": "Nilai Contoh",
        "severity.critical": "Kritis",
        "severity.high": "Tinggi",
        "severity.medium": "Sedang",
        "severity.low": "Rendah",
        "severity.info": "Info",
        "status.passed": "Lulus",
        "status.failed": "Gagal",
        "status.pending": "Menunggu",
        "status.running": "Berjalan",
        "issues.count.one": "{count} masalah",
        "issues.count.other": "{count} masalah",
        "rows.count.one": "{count} baris",
        "rows.count.other": "{count} baris",
        "time.seconds": "{value} detik",
        "time.milliseconds": "{value} ms",
        "common.yes": "Ya",
        "common.no": "Tidak",
        "common.true": "Benar",
        "common.false": "Salah",
    },
)


# ============================================================================
# Turkish
# ============================================================================
TURKISH_CATALOG = LocaleCatalog(
    locale=SupportedLocale.TURKISH,
    messages={
        "report.title": "Doğrulama Raporu",
        "report.generated_at": "Oluşturulma tarihi",
        "report.source": "Veri kaynağı",
        "report.validation_id": "Doğrulama ID",
        "report.generated_by": "Truthound Dashboard tarafından oluşturuldu",
        "summary.title": "Doğrulama Özeti",
        "summary.status": "Durum",
        "summary.total_issues": "Toplam Sorun",
        "summary.pass_rate": "Başarı Oranı",
        "statistics.title": "Veri İstatistikleri",
        "statistics.row_count": "Satır Sayısı",
        "statistics.column_count": "Sütun Sayısı",
        "statistics.duration": "Süre",
        "statistics.started_at": "Başlangıç",
        "statistics.completed_at": "Bitiş",
        "statistics.na": "Mevcut değil",
        "issues.title": "Sorunlar",
        "issues.no_issues": "Sorun bulunamadı. Tüm doğrulamalar başarılı.",
        "issues.column": "Sütun",
        "issues.type": "Sorun Türü",
        "issues.severity": "Önem Derecesi",
        "issues.count": "Sayı",
        "issues.details": "Detaylar",
        "issues.samples": "Örnek Değerler",
        "severity.critical": "Kritik",
        "severity.high": "Yüksek",
        "severity.medium": "Orta",
        "severity.low": "Düşük",
        "severity.info": "Bilgi",
        "status.passed": "Başarılı",
        "status.failed": "Başarısız",
        "status.pending": "Bekliyor",
        "status.running": "Çalışıyor",
        "issues.count.one": "{count} sorun",
        "issues.count.other": "{count} sorun",
        "rows.count.one": "{count} satır",
        "rows.count.other": "{count} satır",
        "time.seconds": "{value} saniye",
        "time.milliseconds": "{value} ms",
        "common.yes": "Evet",
        "common.no": "Hayır",
        "common.true": "Doğru",
        "common.false": "Yanlış",
    },
)
