"""Pydantic schemas for API request/response validation.

This module exports all schemas used in the API layer.
Schemas follow consistent naming conventions:
- *Base: Common fields
- *Create: POST request bodies
- *Update: PUT/PATCH request bodies
- *Response: Response bodies
- *ListResponse: Paginated list responses
"""

from .base import (
    BaseSchema,
    ErrorResponse,
    IDMixin,
    ListResponseWrapper,
    MessageResponse,
    ResponseWrapper,
    TimestampMixin,
)
from .drift import (
    ColumnDriftResult,
    DEFAULT_THRESHOLDS,
    DriftCompareRequest,
    DriftComparisonListItem,
    DriftComparisonListResponse,
    DriftComparisonResponse,
    DriftMethod,
    DriftMethodLiteral,
    DriftResult,
    DriftSourceSummary,
    get_default_threshold,
)
from .history import (
    FailureFrequencyItem,
    HistoryQueryParams,
    HistoryResponse,
    HistorySummary,
    RecentValidation,
    TrendDataPoint,
)
from .profile import (
    ColumnProfile,
    DetectedPattern,
    HistogramBucket,
    ProfileRequest,
    ProfileResponse,
)
from .rule import (
    RuleBase,
    RuleCreate,
    RuleListItem,
    RuleListResponse,
    RuleResponse,
    RuleSummary,
    RuleUpdate,
)
from .schedule import (
    ScheduleActionResponse,
    ScheduleBase,
    ScheduleCreate,
    ScheduleListItem,
    ScheduleListResponse,
    ScheduleResponse,
    ScheduleUpdate,
)
# Phase 5: Glossary schemas
from .glossary import (
    CategoryBase,
    CategoryCreate,
    CategoryListResponse,
    CategoryResponse,
    CategorySummary,
    CategoryUpdate,
    RelatedTermSummary,
    RelationshipBase,
    RelationshipCreate,
    RelationshipListResponse,
    RelationshipResponse,
    RelationshipType,
    TermBase,
    TermCreate,
    TermHistoryListResponse,
    TermHistoryResponse,
    TermListItem,
    TermListResponse,
    TermResponse,
    TermStatus,
    TermSummary,
    TermUpdate,
)
# Phase 5: Catalog schemas
from .catalog import (
    AssetBase,
    AssetCreate,
    AssetListItem,
    AssetListResponse,
    AssetResponse,
    AssetType,
    AssetUpdate,
    ColumnBase,
    ColumnCreate,
    ColumnListResponse,
    ColumnResponse,
    ColumnTermMapping,
    ColumnUpdate,
    QualityLevel,
    SensitivityLevel,
    SourceSummary,
    TagBase,
    TagCreate,
    TagResponse,
)
# Phase 5: Collaboration schemas
from .collaboration import (
    ActivityAction,
    ActivityCreate,
    ActivityListResponse,
    ActivityResponse,
    CommentBase,
    CommentCreate,
    CommentListResponse,
    CommentResponse,
    CommentUpdate,
    ResourceType,
)
from .mask import (
    MaskingStrategy,
    MaskingStrategyLiteral,
    MaskListItem,
    MaskListResponse,
    MaskRequest,
    MaskResponse,
    MaskStatus,
    MaskSummary,
)
from .scan import (
    PIIFinding,
    PIIScanListItem,
    PIIScanListResponse,
    PIIScanRequest,
    PIIScanResponse,
    PIIScanSummary,
    Regulation,
    RegulationViolation,
)
from .schema import (
    ColumnSchema,
    SchemaLearnRequest,
    SchemaResponse,
    SchemaSummary,
    SchemaUpdateRequest,
)
from .source import (
    FieldDefinitionSchema,
    FieldOption,
    FieldType,
    SourceBase,
    SourceCategory,
    SourceCreate,
    SourceListResponse,
    SourceResponse,
    SourceSummary,
    SourceType,
    SourceTypeCategorySchema,
    SourceTypeDefinitionSchema,
    SourceTypesResponse,
    SourceUpdate,
    TestConnectionRequest,
    TestConnectionResponse,
)
from .validation import (
    IssueSeverity,
    ValidationIssue,
    ValidationListItem,
    ValidationListResponse,
    ValidationResponse,
    ValidationRunRequest,
    ValidationStatus,
    ValidationSummary,
)
# Reports
from .reports import (
    AvailableFormatsResponse,
    ReportFormatType,
    ReportGenerateRequest,
    ReportMetadataResponse,
    ReportResponse,
    ReportThemeType,
)
# Maintenance
from .maintenance import (
    CacheClearRequest,
    CacheStatsResponse,
    CleanupResultItem,
    CleanupTriggerRequest,
    MaintenanceReportResponse,
    MaintenanceStatusResponse,
    RetentionPolicyConfig,
    RetentionPolicyResponse,
)
# Schema Evolution
from .schema_evolution import (
    SchemaChangeListResponse,
    SchemaChangeResponse,
    SchemaChangeSeverity,
    SchemaChangeType,
    SchemaEvolutionRequest,
    SchemaEvolutionResponse,
    SchemaEvolutionSummary,
    SchemaVersionListResponse,
    SchemaVersionResponse,
    SchemaVersionSummary,
)
# Rule Suggestion
from .rule_suggestion import (
    ApplyRulesRequest,
    ApplyRulesResponse,
    CrossColumnRuleSuggestion,
    CrossColumnRuleType,
    ExportRulesRequest,
    ExportRulesResponse,
    PresetInfo,
    PresetsResponse,
    RuleCategory,
    RuleExportFormat,
    RulePreset,
    RuleSuggestionRequest,
    RuleSuggestionResponse,
    StrictnessLevel,
    SuggestedRule,
    SuggestionStats,
)
# Profile Comparison
from .profile_comparison import (
    ColumnComparison,
    ColumnComparisonSummary,
    ColumnTrend,
    LatestComparisonResponse,
    ProfileComparisonRequest,
    ProfileComparisonResponse,
    ProfileListResponse,
    ProfileSummary,
    ProfileTrendPoint,
    ProfileTrendRequest,
    ProfileTrendResponse,
    TrendDirection,
)
# Advanced Notifications
from .notifications_advanced import (
    AcknowledgeRequest,
    AdvancedNotificationStats,
    DeduplicationConfigCreate,
    DeduplicationConfigListResponse,
    DeduplicationConfigResponse,
    DeduplicationConfigUpdate,
    DeduplicationPolicy,
    DeduplicationStats,
    DeduplicationStrategy,
    EscalationEventBase,
    EscalationIncidentBase,
    EscalationIncidentListResponse,
    EscalationIncidentResponse,
    EscalationLevelBase,
    EscalationPolicyBase,
    EscalationPolicyCreate,
    EscalationPolicyListResponse,
    EscalationPolicyResponse,
    EscalationPolicyUpdate,
    EscalationState,
    EscalationStats,
    EscalationTargetBase,
    ResolveRequest,
    RoutingRuleCreate,
    RoutingRuleListResponse,
    RoutingRuleResponse,
    RoutingRuleUpdate,
    RuleConfig,
    RuleType,
    RuleTypeInfo,
    RuleTypesResponse,
    TargetType,
    ThrottlingConfigCreate,
    ThrottlingConfigListResponse,
    ThrottlingConfigResponse,
    ThrottlingConfigUpdate,
    ThrottlingStats,
)
# OpenLineage Export
from .openlineage import (
    OpenLineageDataset,
    OpenLineageEmitRequest,
    OpenLineageEmitResponse,
    OpenLineageEvent,
    OpenLineageExportFormat,
    OpenLineageExportRequest,
    OpenLineageExportResponse,
    OpenLineageJob,
    OpenLineageRun,
    OpenLineageWebhookConfig,
    RunState,
    build_dataset_namespace,
)
# Cross-Alerts
from .cross_alerts import (
    AlertType,
    AutoTriggerConfig,
    AutoTriggerConfigCreate,
    AutoTriggerConfigUpdate,
    AutoTriggerEvent,
    AutoTriggerEventListResponse,
    AutoTriggerThresholds,
    CorrelatedAlert,
    CorrelationStrength,
    CrossAlertCorrelation,
    CrossAlertCorrelationListResponse,
    CrossAlertSummary,
    TriggerDirection,
)
# Triggers
from .triggers import (
    CompositeTriggerConfig,
    CronTriggerConfig,
    DataChangeTriggerConfig,
    EventTriggerConfig,
    IntervalTriggerConfig,
    ManualTriggerConfig,
    TriggerConfig,
    TriggerConfigCreate,
    TriggerEvaluationResult,
    TriggerOperator,
    TriggerResponse,
    TriggerState,
    TriggerType,
    parse_trigger_config,
)
# Plugins
from .plugins import (
    CustomReporterCreate,
    CustomReporterListResponse,
    CustomReporterResponse,
    CustomReporterUpdate,
    CustomValidatorCreate,
    CustomValidatorListResponse,
    CustomValidatorResponse,
    CustomValidatorUpdate,
    MarketplaceSearchRequest,
    MarketplaceStats,
    PluginCreate,
    PluginInstallRequest,
    PluginInstallResponse,
    PluginListResponse,
    PluginPermission,
    PluginResponse,
    PluginSource,
    PluginStatus,
    PluginSummary,
    PluginType,
    PluginUninstallRequest,
    PluginUninstallResponse,
    PluginUpdate,
    PluginUpdateCheckResponse,
    ReporterGenerateRequest,
    ReporterGenerateResponse,
    ReporterOutputFormat,
    SecurityLevel,
    ValidatorTestRequest,
    ValidatorTestResponse,
)

__all__ = [
    # Base
    "BaseSchema",
    "IDMixin",
    "TimestampMixin",
    "ResponseWrapper",
    "ListResponseWrapper",
    "ErrorResponse",
    "MessageResponse",
    # Source
    "SourceType",
    "SourceCategory",
    "FieldType",
    "SourceBase",
    "SourceCreate",
    "SourceUpdate",
    "SourceResponse",
    "SourceListResponse",
    "SourceSummary",
    # Source Type Definitions (dynamic forms)
    "FieldOption",
    "FieldDefinitionSchema",
    "SourceTypeDefinitionSchema",
    "SourceTypeCategorySchema",
    "SourceTypesResponse",
    "TestConnectionRequest",
    "TestConnectionResponse",
    # Rule
    "RuleBase",
    "RuleCreate",
    "RuleUpdate",
    "RuleResponse",
    "RuleListItem",
    "RuleListResponse",
    "RuleSummary",
    # Validation
    "ValidationStatus",
    "IssueSeverity",
    "ValidationIssue",
    "ValidationRunRequest",
    "ValidationSummary",
    "ValidationResponse",
    "ValidationListItem",
    "ValidationListResponse",
    # Schema
    "ColumnSchema",
    "SchemaLearnRequest",
    "SchemaUpdateRequest",
    "SchemaResponse",
    "SchemaSummary",
    # Profile
    "ProfileRequest",
    "ColumnProfile",
    "ProfileResponse",
    "DetectedPattern",
    "HistogramBucket",
    # Data Masking
    "MaskingStrategy",
    "MaskingStrategyLiteral",
    "MaskStatus",
    "MaskRequest",
    "MaskSummary",
    "MaskResponse",
    "MaskListItem",
    "MaskListResponse",
    # PII Scan
    "Regulation",
    "PIIScanRequest",
    "PIIFinding",
    "RegulationViolation",
    "PIIScanSummary",
    "PIIScanResponse",
    "PIIScanListItem",
    "PIIScanListResponse",
    # History
    "TrendDataPoint",
    "FailureFrequencyItem",
    "RecentValidation",
    "HistorySummary",
    "HistoryResponse",
    "HistoryQueryParams",
    # Drift
    "DriftMethod",
    "DriftMethodLiteral",
    "DEFAULT_THRESHOLDS",
    "get_default_threshold",
    "DriftCompareRequest",
    "ColumnDriftResult",
    "DriftResult",
    "DriftSourceSummary",
    "DriftComparisonResponse",
    "DriftComparisonListItem",
    "DriftComparisonListResponse",
    # Schedule
    "ScheduleBase",
    "ScheduleCreate",
    "ScheduleUpdate",
    "ScheduleResponse",
    "ScheduleListItem",
    "ScheduleListResponse",
    "ScheduleActionResponse",
    # Phase 5: Glossary
    "TermStatus",
    "RelationshipType",
    "CategoryBase",
    "CategoryCreate",
    "CategoryUpdate",
    "CategorySummary",
    "CategoryResponse",
    "CategoryListResponse",
    "TermBase",
    "TermCreate",
    "TermUpdate",
    "TermSummary",
    "RelatedTermSummary",
    "TermResponse",
    "TermListItem",
    "TermListResponse",
    "RelationshipBase",
    "RelationshipCreate",
    "RelationshipResponse",
    "RelationshipListResponse",
    "TermHistoryResponse",
    "TermHistoryListResponse",
    # Phase 5: Catalog
    "AssetType",
    "SensitivityLevel",
    "QualityLevel",
    "TagBase",
    "TagCreate",
    "TagResponse",
    "ColumnBase",
    "ColumnCreate",
    "ColumnUpdate",
    "ColumnTermMapping",
    "ColumnResponse",
    "ColumnListResponse",
    "SourceSummary",
    "AssetBase",
    "AssetCreate",
    "AssetUpdate",
    "AssetResponse",
    "AssetListItem",
    "AssetListResponse",
    # Phase 5: Collaboration
    "ResourceType",
    "ActivityAction",
    "CommentBase",
    "CommentCreate",
    "CommentUpdate",
    "CommentResponse",
    "CommentListResponse",
    "ActivityResponse",
    "ActivityListResponse",
    "ActivityCreate",
    # Reports
    "ReportFormatType",
    "ReportThemeType",
    "ReportGenerateRequest",
    "ReportMetadataResponse",
    "ReportResponse",
    "AvailableFormatsResponse",
    # Maintenance
    "RetentionPolicyConfig",
    "RetentionPolicyResponse",
    "CleanupResultItem",
    "MaintenanceReportResponse",
    "CleanupTriggerRequest",
    "MaintenanceStatusResponse",
    "CacheStatsResponse",
    "CacheClearRequest",
    # Schema Evolution
    "SchemaChangeType",
    "SchemaChangeSeverity",
    "SchemaVersionResponse",
    "SchemaVersionSummary",
    "SchemaVersionListResponse",
    "SchemaChangeResponse",
    "SchemaChangeListResponse",
    "SchemaEvolutionRequest",
    "SchemaEvolutionResponse",
    "SchemaEvolutionSummary",
    # Rule Suggestion
    "SuggestedRule",
    "CrossColumnRuleSuggestion",
    "CrossColumnRuleType",
    "RuleSuggestionRequest",
    "RuleSuggestionResponse",
    "ApplyRulesRequest",
    "ApplyRulesResponse",
    "SuggestionStats",
    "RuleCategory",
    "RulePreset",
    "StrictnessLevel",
    "RuleExportFormat",
    "ExportRulesRequest",
    "ExportRulesResponse",
    "PresetInfo",
    "PresetsResponse",
    # Profile Comparison
    "TrendDirection",
    "ProfileSummary",
    "ProfileListResponse",
    "ColumnComparison",
    "ColumnComparisonSummary",
    "ProfileComparisonRequest",
    "ProfileComparisonResponse",
    "ProfileTrendPoint",
    "ColumnTrend",
    "ProfileTrendRequest",
    "ProfileTrendResponse",
    "LatestComparisonResponse",
    # Advanced Notifications
    "RuleType",
    "DeduplicationStrategy",
    "DeduplicationPolicy",
    "EscalationState",
    "TargetType",
    "RuleConfig",
    "RoutingRuleCreate",
    "RoutingRuleUpdate",
    "RoutingRuleResponse",
    "RoutingRuleListResponse",
    "RuleTypeInfo",
    "RuleTypesResponse",
    "DeduplicationConfigCreate",
    "DeduplicationConfigUpdate",
    "DeduplicationConfigResponse",
    "DeduplicationConfigListResponse",
    "DeduplicationStats",
    "ThrottlingConfigCreate",
    "ThrottlingConfigUpdate",
    "ThrottlingConfigResponse",
    "ThrottlingConfigListResponse",
    "ThrottlingStats",
    "EscalationTargetBase",
    "EscalationLevelBase",
    "EscalationPolicyBase",
    "EscalationPolicyCreate",
    "EscalationPolicyUpdate",
    "EscalationPolicyResponse",
    "EscalationPolicyListResponse",
    "EscalationEventBase",
    "EscalationIncidentBase",
    "EscalationIncidentResponse",
    "EscalationIncidentListResponse",
    "AcknowledgeRequest",
    "ResolveRequest",
    "EscalationStats",
    "AdvancedNotificationStats",
    # OpenLineage Export
    "RunState",
    "OpenLineageDataset",
    "OpenLineageJob",
    "OpenLineageRun",
    "OpenLineageEvent",
    "OpenLineageExportFormat",
    "OpenLineageExportRequest",
    "OpenLineageExportResponse",
    "OpenLineageWebhookConfig",
    "OpenLineageEmitRequest",
    "OpenLineageEmitResponse",
    "build_dataset_namespace",
    # Cross-Alerts
    "AlertType",
    "CorrelationStrength",
    "TriggerDirection",
    "CorrelatedAlert",
    "CrossAlertCorrelation",
    "CrossAlertCorrelationListResponse",
    "AutoTriggerThresholds",
    "AutoTriggerConfig",
    "AutoTriggerConfigCreate",
    "AutoTriggerConfigUpdate",
    "AutoTriggerEvent",
    "AutoTriggerEventListResponse",
    "CrossAlertSummary",
    # Triggers
    "TriggerType",
    "TriggerOperator",
    "CronTriggerConfig",
    "IntervalTriggerConfig",
    "DataChangeTriggerConfig",
    "EventTriggerConfig",
    "CompositeTriggerConfig",
    "ManualTriggerConfig",
    "TriggerConfig",
    "TriggerState",
    "TriggerEvaluationResult",
    "TriggerConfigCreate",
    "TriggerResponse",
    "parse_trigger_config",
    # Plugins
    "PluginType",
    "PluginStatus",
    "PluginSource",
    "SecurityLevel",
    "PluginPermission",
    "ReporterOutputFormat",
    "PluginCreate",
    "PluginUpdate",
    "PluginResponse",
    "PluginListResponse",
    "PluginSummary",
    "PluginInstallRequest",
    "PluginInstallResponse",
    "PluginUninstallRequest",
    "PluginUninstallResponse",
    "PluginUpdateCheckResponse",
    "CustomValidatorCreate",
    "CustomValidatorUpdate",
    "CustomValidatorResponse",
    "CustomValidatorListResponse",
    "ValidatorTestRequest",
    "ValidatorTestResponse",
    "CustomReporterCreate",
    "CustomReporterUpdate",
    "CustomReporterResponse",
    "CustomReporterListResponse",
    "ReporterGenerateRequest",
    "ReporterGenerateResponse",
    "MarketplaceSearchRequest",
    "MarketplaceStats",
]
